import type { MonthRangeSelection } from "@/types/admin-analytics";

export const ANALYTICS_TEXT = {
    TREND_TITLE: "Xu hướng mượn sách",
    TREND_BORROWED: "Đã mượn",
    TREND_RETURNED: "Đã trả",
    TREND_OVERDUE: "Quá hạn",
    MONTHS: ["Th1", "Th2", "Th3", "Th4", "Th5", "Th6"],
    STATUS_TITLE: "Trạng thái thư viện",
    STATUS_CAPACITY: "Công suất",
    STATUS_AVAILABLE: "Có sẵn (70%)",
    STATUS_BORROWING: "Đang mượn (15%)",
    STATUS_RESERVED: "Đã đặt (10%)",
    STATUS_MAINTENANCE: "Bảo trì (5%)",
    STATUS_AVAILABLE_LABEL: "Có sẵn",
    STATUS_BORROWING_LABEL: "Đang mượn",
    STATUS_RESERVED_LABEL: "Đã đặt",
    STATUS_MAINTENANCE_LABEL: "Bảo trì",
    CATEGORIES_TITLE: "Thể loại nổi bật",
    MOST_BORROWED_TITLE: "Sách được mượn nhiều",
    TABLE_BOOK: "Sách",
    TABLE_TITLE_AUTHOR: "Tựa sách & Tác giả",
    TABLE_BORROWS: "Lượt mượn",
    TABLE_STATUS: "Trạng thái",
    ACTIVITIES_TITLE: "Hoạt động gần đây",
    AI_TITLE: "Gợi ý AI",
    AI_BADGE: "THỜI GIAN THỰC",
    AI_BORROW_PREFIX: "Lượt mượn tăng ",
    AI_BORROW_VALUE: "18%",
    AI_BORROW_SUFFIX: " trong tuần này so với tuần trước.",
    AI_SCIENCE_PREFIX: "Nhóm sách ",
    AI_SCIENCE_VALUE: "Khoa học",
    AI_SCIENCE_SUFFIX: " có thể cần bổ sung thêm bản sao dựa trên tốc độ mượn.",
    AI_TRAFFIC_PREFIX: "Lượng truy cập thư viện thường đạt đỉnh trong khung ",
    AI_TRAFFIC_VALUE: "14:00-16:00",
    AI_TRAFFIC_SUFFIX: ".",
    PAGE_TITLE: "Tổng quan thống kê",
    PAGE_DESCRIPTION: "Theo dõi tình hình mượn trả, tồn kho, thành viên và các cảnh báo vận hành của thư viện.",
    BREADCRUMB_LABEL: "Thống kê",
    REPORT_DATE: "24/10/2023",
    TIME_RANGE_LABEL: "Khoảng thời gian thống kê",
    TIME_RANGE_1_MONTH: "1 tháng",
    TIME_RANGE_3_MONTHS: "3 tháng",
    TIME_RANGE_6_MONTHS: "6 tháng",
    TIME_RANGE_1_YEAR: "1 năm",
    CALENDAR_FROM_LABEL: "Từ:",
    CALENDAR_TO_LABEL: "Đến:",
    CALENDAR_RESET_LABEL: "Về hiện tại",
    SUMMARY_LABEL: "Tổng hợp thống kê",
    TREND_ARIA: "Xu hướng mượn sách từ tháng 1 đến tháng 6",
    STATUS_ARIA: "Biểu đồ công suất thư viện",
};

export const CURRENT_MONTH_RANGE: MonthRangeSelection = {
    startYear: 2026,
    startMonth: 5,
    endYear: 2026,
    endMonth: 6,
};

export const MONTH_PICKER_OPTIONS = [
    { value: 1, label: "Th1" },
    { value: 2, label: "Th2" },
    { value: 3, label: "Th3" },
    { value: 4, label: "Th4" },
    { value: 5, label: "Th5" },
    { value: 6, label: "Th6" },
    { value: 7, label: "Th7" },
    { value: 8, label: "Th8" },
    { value: 9, label: "Th9" },
    { value: 10, label: "Th10" },
    { value: 11, label: "Th11" },
    { value: 12, label: "Th12" },
] as const;

export const YEAR_PICKER_OPTIONS = [2022, 2023, 2024, 2025, 2026] as const;
