export const FORGOT_PASSWORD = {
    HEADING: "Quên mật khẩu",
    SUBHEADING: "Nhập địa chỉ email của bạn để nhận mã xác nhận (OTP) đặt lại mật khẩu.",
    EMAIL_LABEL: "Email",
    EMAIL_PLACEHOLDER: "Email của bạn",
    OTP_LABEL: "Mã xác nhận (OTP)",
    OTP_PLACEHOLDER: "Nhập mã gồm 6 số",
    NEW_PASSWORD_LABEL: "Mật khẩu mới",
    NEW_PASSWORD_PLACEHOLDER: "Mật khẩu mới của bạn",
    CONFIRM_PASSWORD_LABEL: "Xác nhận mật khẩu",
    CONFIRM_PASSWORD_PLACEHOLDER: "Xác nhận mật khẩu mới",
    SUBMIT_EMAIL_BTN: "Gửi mã xác nhận",
    SUBMIT_RESET_BTN: "Đặt lại mật khẩu",
    BACK_TO_LOGIN: "Quay lại đăng nhập",
    VALIDATION: {
        EMAIL_REQUIRED: "Email không được để trống.",
        EMAIL_INVALID: "Email không hợp lệ.",
        OTP_REQUIRED: "Mã OTP không được để trống.",
        OTP_LENGTH: "Mã OTP phải có 6 chữ số.",
        PASSWORD_REQUIRED: "Mật khẩu không được để trống.",
        PASSWORD_MIN_LENGTH: "Mật khẩu phải có ít nhất 8 ký tự.",
        PASSWORD_MISMATCH: "Mật khẩu xác nhận không khớp.",
    },
    SUCCESS: "Đặt lại mật khẩu thành công! Vui lòng đăng nhập lại.",
};
