export const REGISTER = {
    HEADING: "Tạo tài khoản",
    FULL_NAME_LABEL: "Họ và tên",
    FULL_NAME_PLACEHOLDER: "Nguyễn Văn A",
    PHONE_LABEL: "Số điện thoại",
    PHONE_PLACEHOLDER: "0901234567",
    EMAIL_LABEL: "Email",
    EMAIL_PLACEHOLDER: "Email của bạn",
    PASSWORD_LABEL: "Mật khẩu",
    PASSWORD_PLACEHOLDER: "Nhập mật khẩu",
    CONFIRM_PASSWORD_LABEL: "Xác nhận mật khẩu",
    CONFIRM_PASSWORD_PLACEHOLDER: "Xác nhận mật khẩu",
    SUBMIT_BTN: "Đăng ký →",
    LOADING_BTN: "Đang xử lý...",
    ERROR_MSG: "Đăng ký thất bại. Vui lòng thử lại.",
    ALREADY_HAVE_ACCOUNT: "Đã có tài khoản?",
    LOGIN_LINK: "Đăng nhập ngay",
    ERROR_ICON: "⚠️",
};
