export const ADMIN_ANALYTICS = {
    TREND_TITLE: "Xu hướng mượn sách",
    TREND_BORROWED: "Đã mượn",
    TREND_RETURNED: "Đã trả",
    TREND_OVERDUE: "Quá hạn",
    MONTHS: ["Th1", "Th2", "Th3", "Th4", "Th5", "Th6"],
    STATUS_TITLE: "Trạng thái thư viện",
    STATUS_CAPACITY: "Công suất",
    STATUS_AVAILABLE: "Có sẵn (70%)",
    STATUS_BORROWING: "Đang mượn (15%)",
    STATUS_RESERVED: "Đã đặt (10%)",
    STATUS_MAINTENANCE: "Bảo trì (5%)",
    STATUS_AVAILABLE_LABEL: "Có sẵn",
    STATUS_BORROWING_LABEL: "Đang mượn",
    STATUS_RESERVED_LABEL: "Đã đặt",
    STATUS_MAINTENANCE_LABEL: "Bảo trì",
    CATEGORIES_TITLE: "Thể loại nổi bật",
    MOST_BORROWED_TITLE: "Sách được mượn nhiều",
    TABLE_BOOK: "Sách",
    TABLE_TITLE_AUTHOR: "Tựa sách & Tác giả",
    TABLE_BORROWS: "Lượt mượn",
    TABLE_STATUS: "Trạng thái",
    ACTIVITIES_TITLE: "Hoạt động gần đây",
    AI_TITLE: "Gợi ý AI",
    AI_BADGE: "THỜI GIAN THỰC",
    AI_BORROW_PREFIX: "Lượt mượn tăng ",
    AI_BORROW_VALUE: "18%",
    AI_BORROW_SUFFIX: " trong tuần này so với tuần trước.",
    AI_SCIENCE_PREFIX: "Nhóm sách ",
    AI_SCIENCE_VALUE: "Khoa học",
    AI_SCIENCE_SUFFIX: " có thể cần bổ sung thêm bản sao dựa trên tốc độ mượn.",
    AI_TRAFFIC_PREFIX: "Lượng truy cập thư viện thường đạt đỉnh trong khung ",
    AI_TRAFFIC_VALUE: "14:00-16:00",
    AI_TRAFFIC_SUFFIX: ".",
    PAGE_TITLE: "Tổng quan thống kê",
    PAGE_DESCRIPTION: "Theo dõi tình hình mượn trả, tồn kho, thành viên và các cảnh báo vận hành của thư viện.",
    BREADCRUMB_LABEL: "Thống kê",
    REPORT_DATE: "24/10/2023",
    TIME_RANGE_LABEL: "Khoảng thời gian thống kê",
    TIME_RANGE_1_MONTH: "1 tháng",
    TIME_RANGE_3_MONTHS: "3 tháng",
    TIME_RANGE_6_MONTHS: "6 tháng",
    TIME_RANGE_1_YEAR: "1 năm",
    CALENDAR_FROM_LABEL: "Từ:",
    CALENDAR_TO_LABEL: "Đến:",
    CALENDAR_RESET_LABEL: "Về hiện tại",
    SUMMARY_LABEL: "Tổng hợp thống kê",
    TREND_ARIA: "Xu hướng mượn sách từ tháng 1 đến tháng 6",
    STATUS_ARIA: "Biểu đồ công suất thư viện",
    MONTH_OPTIONS: {
        M1: "Th1",
        M2: "Th2",
        M3: "Th3",
        M4: "Th4",
        M5: "Th5",
        M6: "Th6",
        M7: "Th7",
        M8: "Th8",
        M9: "Th9",
        M10: "Th10",
        M11: "Th11",
        M12: "Th12",
    },
    MONTH_FORMAT: {
        PREFIX: "Tháng ",
        YEAR_SEPARATOR: " năm ",
    },
    EXPORT: {
        FORMAT_LABEL: "Định dạng file xuất",
        RECORD_BTN: "Xuất bản ghi",
        FORMAT_CSV: "CSV",
        FORMAT_JSON: "JSON",
        FILENAME: "thong-ke-thu-vien.csv",
        CSV_HEADERS: {
            PERIOD_TITLE: "Khoảng thời gian",
            PERIOD_VAL: "Giá trị",
            SUMMARY_TITLE: "Tổng hợp thống kê",
            SUMMARY_METRIC: "Chỉ số",
            SUMMARY_VAL: "Giá trị",
            SUMMARY_NOTE: "Ghi chú",
            SUMMARY_UP: "Tăng ",
            TREND_TITLE: "Biểu đồ xu hướng mượn sách",
            TREND_TIME: "Thời gian",
            TREND_BORROWED: "Đã mượn",
            TREND_RETURNED: "Đã trả",
            TREND_OVERDUE: "Quá hạn",
            STATUS_TITLE: "Biểu đồ trạng thái thư viện",
            STATUS_STATE: "Trạng thái",
            STATUS_RATE: "Tỷ lệ",
            STATUS_AVAILABLE: "Có sẵn",
            STATUS_BORROWING: "Đang mượn",
            STATUS_RESERVED: "Đã đặt",
            STATUS_MAINTENANCE: "Bảo trì",
            CAT_TITLE: "Thể loại nổi bật",
            CAT_NAME: "Thể loại",
            CAT_RATE: "Tỷ lệ",
            BOOK_TITLE: "Sách được mượn nhiều",
            BOOK_NAME: "Tựa sách",
            BOOK_AUTHOR: "Tác giả",
            BOOK_BORROWS: "Lượt mượn",
            BOOK_STATUS: "Trạng thái",
            ACT_TITLE: "Hoạt động gần đây",
            ACT_NAME: "Hoạt động",
            ACT_DETAIL: "Chi tiết",
            ACT_TIME: "Thời gian",
        },
    },
};
