export const ADMIN_AUDIT_LOGS = {
    TOPBAR_TITLE: "Cổng quản trị",
    BREADCRUMB_LABEL: "Nhật ký hệ thống",
    PAGE_TITLE: "Nhật ký kiểm toán hệ thống",
    PAGE_DESCRIPTION:
        "Bản ghi theo trình tự thời gian về sự kiện hệ thống, hoạt động người dùng và các thao tác vận hành liên quan đến bảo mật trên toàn nền tảng.",
    QUICK_SEARCH_PLACEHOLDER: "Tìm nhanh ID hoặc người dùng...",
    TOPBAR_NOTIFICATIONS: "Thông báo",
    TOPBAR_SETTINGS: "Cài đặt",
    ADVANCED_FILTERS: "Bộ lọc nâng cao",
    EXPORT_RECORD: "Xuất bản ghi",
    EXPORT_FILENAME: "nhat-ky-kiem-toan-da-loc.csv",
    EXPORT_FORMAT_LABEL: "Định dạng file",
    EXPORT_FORMAT_CSV: "CSV",
    EXPORT_FORMAT_JSON: "JSON",
    DETAIL_TITLE: "Xem chi tiết bản ghi",
    DETAIL_ACTION: "Xem chi tiết",
    FILTERS: {
        DATE_RANGE: "Khoảng thời gian",
        DATE_12_HOURS: "12 giờ",
        DATE_1_DAY: "1 ngày",
        DATE_3_DAYS: "3 ngày",
        DATE_7_DAYS: "7 ngày",
        DATE_ALL_TIME: "Từ trước tới nay",
        USER_ENTITY: "Người dùng / Đối tượng",
        ALL_USERS: "Tất cả",
        USERS: "Người dùng",
        ADMINS: "Quản trị viên",
        AUTOMATION: "Tự động hóa hệ thống",
        ACTION_TYPE: "Thao tác",
        ALL_ACTIONS: "Tất cả",
        AUTH_LOGIN: "Đăng nhập",
        RECORD_UPDATE: "Cập nhật bản ghi",
        PERMISSION_CHANGE: "Thay đổi quyền",
        KEYWORD: "Tìm kiếm",
        KEYWORD_PLACEHOLDER: "VD: '192.168.1.1' hoặc 'xoa_bo_du_lieu'",
    },
    TABLE: {
        TIMESTAMP: "Thời điểm",
        USER_ENTITY: "Người dùng / Đối tượng",
        ACTION: "Thao tác",
        TARGET_OBJECT: "Hành động",
        IP_ADDRESS: "Địa chỉ IP",
        RESULT: "Kết quả",
        PAGINATION_SUMMARY: "Hiển thị {start}-{end} trong {total} bản ghi",
        EMPTY_PAGE: "Không tìm thấy bản ghi nào phù hợp.",
        PAGE_LABEL: "Trang",
        PREVIOUS_PAGE: "Trang trước",
        NEXT_PAGE: "Trang sau",
    },
    RESULT: {
        SUCCESS: "Thành công",
        FAILED: "Thất bại",
        BLOCKED: "Đã chặn",
    },
    DETAIL: {
        TIMESTAMP: "Thời điểm ghi nhận",
        ACTOR: "Người thực hiện",
        ACTION: "Thao tác",
        TARGET: "Hành động",
        IP_ADDRESS: "Địa chỉ IP",
        RESULT: "Kết quả",
        DESCRIPTION: "Mô tả",
    },
    SYSTEM_LOGS: {
        PAGE_TITLE: "Nhật ký hệ thống",
        PAGE_DESCRIPTION: "Theo dõi và quản lý lịch sử hoạt động của người dùng trên hệ thống",
        TABLE_TIME: "Thời gian",
        TABLE_ACTOR: "Người thực hiện",
        TABLE_ACTION: "Hành động",
        TABLE_DETAILS: "Chi tiết",
        TABLE_IP: "IP",
        ERROR_FETCH: "Lỗi khi tải danh sách nhật ký hệ thống",
        BTN_RETRY: "Thử lại",
        EMPTY_STATE: "Chưa có nhật ký hoạt động nào",
        GUEST: "Khách",
        NA_IP: "Chưa ghi nhận",
        PAGE_INFO: "Trang",
        BTN_PREV: "Trước",
        BTN_NEXT: "Sau",
    },
};
