export const ADMIN_BORROW_MANAGEMENT = {
    HEADER: {
        TITLE: "Lượt mượn",
        DESCRIPTION: "Quản lý danh sách mượn trả sách trong hệ thống",
        CREATE_BTN: "Tạo phiếu mượn mới",
    },
    FILTERS: {
        SEARCH_PLACEHOLDER: "Tìm theo tên thành viên, SĐT, Mã phiếu...",
        STATUS_ALL: "Trạng thái",
        STATUS_PENDING: "Chờ duyệt",
        STATUS_READY: "Chờ lấy",
        STATUS_BORROWED: "Đang mượn",
        STATUS_OVERDUE: "Quá hạn",
        STATUS_RETURNED: "Đã trả",
        DATE_SEPARATOR: "—",
        BTN_MORE_FILTER: "Lọc thêm",
        BTN_CLEAR_FILTER: "Bỏ lọc",
        BTN_APPLY_FILTER: "Lọc",
        LABEL_FROM: "Từ:",
        LABEL_TO: "Đến:",
        PAGINATION_PAGE: "Trang",
        STATUS_PARTIALLY_RETURNED: "Trả một phần",
        STATUS_CANCELLED: "Đã hủy",
        STATUS_REJECTED: "Đã từ chối",
    },
    TABLE: {
        COL_MEMBER: "Thành viên",
        COL_BOOK: "Sách mượn",
        COL_BORROW_DATE: "Ngày mượn",
        COL_DUE_DATE: "Hạn trả",
        COL_STATUS: "Trạng thái",
        COL_ACTIONS: "Thao tác",
        BTN_VIEW: "Xem chi tiết",
        BTN_RETURN: "Xử lý trả sách",
        BTN_REMIND: "Gửi nhắc nhở",
        BTN_CONFIRM_HANDOVER: "Xác nhận giao sách",
        PAGINATION_INFO: "Hiển thị 1-3 trong số 124 lượt mượn",
        STATUS_BORROWED: "Đang mượn",
        STATUS_OVERDUE: "Quá hạn",
        STATUS_READY: "Chờ lấy",
        STATUS_RETURNED: "Đã trả",
        STATUS_PENDING: "Chờ duyệt",
        STATUS_PENDING_RENEWAL: "Chờ duyệt gia hạn",
        NO_DATE: "—",
        EMPTY_STATE: "Không có dữ liệu lượt mượn",
        GUEST_BADGE: "KHÁCH",
        STATUS_PARTIALLY_RETURNED: "Trả một phần",
        STATUS_CANCELLED: "Đã hủy",
        STATUS_REJECTED: "Đã từ chối",
    },
    MODAL: {
        CREATE_TITLE: "Tạo phiếu mượn mới",
        BTN_CANCEL: "Hủy",
        BTN_CREATE: "Tạo phiếu mượn",
        CLOSE: "✕",
        LABEL_MEMBER_CODE: "Mã thành viên",
        PLACEHOLDER_MEMBER_CODE: "#MB-...",
        LABEL_BOOK_TITLE: "Tên sách",
        PLACEHOLDER_BOOK_TITLE: "Nhập tên sách...",
        LABEL_DUE_DATE: "Ngày hẹn trả",
        PLACEHOLDER_DUE_DATE: "dd/mm/yyyy",
        LABEL_PHONE: "Số điện thoại",
        LABEL_FULL_NAME: "Họ và tên",
        LABEL_EMAIL: "Email",
        LABEL_BOOK_BARCODE: "Mã vạch sách",
        HINT_OPTIONAL_CREATE: "(Tuỳ chọn nếu tạo mới)",
        HINT_OPTIONAL: "(Tuỳ chọn)",
        HINT_MULTIPLE_BARCODE: "Phân cách nhiều mã vạch bằng dấu phẩy (,)",
    },
    DETAIL_MODAL: {
        TITLE: "Chi tiết lượt mượn",
        ORDER_CODE: "Mã phiếu: ",
        SECTION_MEMBER: "Thông tin người mượn",
        MEMBER_NAME: "Họ tên:",
        MEMBER_CODE: "Mã thẻ/SĐT:",
        MEMBER_PHONE: "Số điện thoại:",
        SECTION_BORROW_INFO: "Thông tin mượn trả",
        CREATED_AT: "Ngày tạo:",
        DUE_DATE: "Ngày hẹn trả:",
        STATUS: "Trạng thái:",
        SECTION_BOOKS: "Danh sách sách mượn",
        BOOK_TITLE: "Tên sách",
        BOOK_AUTHOR: "Tác giả",
        BOOK_BARCODE: "Mã vạch",
        BOOK_STATUS: "Trạng thái",
        NO_BOOKS: "Không có dữ liệu sách",
        SECTION_FEE: "Chi phí",
        FEE_RENT: "Tiền thuê:",
        FEE_DISCOUNT: "Giảm giá:",
        FEE_OVERDUE: "Phạt quá hạn :",
        FEE_DEPOSIT: "Tiền cọc (đã thu):",
        FEE_PAID_ONLINE: "Đã thanh toán thêm:",
        FEE_TOTAL: "Tổng phí:",
        FEE_COLLECT: "Cần thu thêm:",
        FEE_REFUND: "Hoàn lại khách:",
        FEE_SETTLED: "Hoàn tất thanh toán",
        GUEST_BADGE: "KHÁCH",
    },
    RETURN_BOOK_MODAL: {
        TITLE: "Xác nhận trả sách",
        BTN_CONFIRM: "Xác nhận trả sách",
        ORDER_CODE: "Mã phiếu mượn",
        BOOK_STATUS_TITLE: "Tình trạng sách trả",
        SELECTING_RETURN: "Đang chọn trả:",
        BOOKS_UNIT: "cuốn",
        ALREADY_RETURNED: "Đã trả trước đó",
        BARCODE: "Mã vạch:",
        CONDITION: "Tình trạng",
        COND_NORMAL: "Bình thường",
        COND_DAMAGED: "Hư hỏng",
        COND_LOST: "Làm mất",
        NOTE_OPTIONAL: "Ghi chú (Tùy chọn)",
        GENERAL_NOTE: "Ghi chú chung cho phiếu trả",
        NOTICE: "Lưu ý:",
        NOTICE_DESC:
            "Hệ thống sẽ tự động tính toán phí phạt quá hạn (nếu có) và phí đền bù dựa trên tình trạng hư hỏng hoặc làm mất sách theo chính sách mượn sách.",
        BTN_CANCEL: "Hủy",
        ERROR_FETCH: "Đã có lỗi xảy ra khi tải chi tiết phiếu mượn",
        ERROR_NO_BOOK_SELECTED: "Vui lòng chọn ít nhất 1 cuốn sách để trả",
        ERROR_RETURN_FAILED: "Xác nhận trả sách thất bại.",
        ERROR_GENERAL: "Đã có lỗi xảy ra. Vui lòng thử lại.",
    },
    RETURN_INVOICE_MODAL: {
        TITLE: "Hóa Đơn Trả Sách",
        ORDER_CODE: "Mã phiếu:",
        COST_SUMMARY: "Tóm tắt chi phí",
        RENT_FEE: "Tiền thuê sách:",
        FINE_FEE: "Tổng tiền phạt:",
        TOTAL_COST: "Tổng chi phí:",
        DEPOSIT_PAID: "Tiền cọc đã thu:",
        REQUIRE_COLLECT: "* Vui lòng thu số tiền này từ người dùng.",
        REQUIRE_REFUND: "* Vui lòng trả lại số tiền này cho người dùng.",
        CASH_CONFIRMED: "Đã xác nhận giao dịch bằng Tiền mặt",
        SCAN_VNPAY: "Quét mã để thanh toán VNPay",
        OPEN_LINK_NEW_TAB: "Mở link thanh toán trong tab mới",
        BTN_COMPLETE: "Hoàn tất",
        BTN_CASH_PAY: "Khách trả Tiền mặt",
        BTN_CASH_REFUND: "Xác nhận đã trả lại Tiền mặt",
        BTN_VNPAY: "Khách quét VNPay",
        STATUS_PROCESSING: "Đang xử lý...",
        STATUS_GENERATING: "Đang tạo...",
        SUCCESS_VNPAY: "Đã tạo mã QR thanh toán VNPay",
        SUCCESS_VNPAY_POLLING: "Thanh toán VNPay thành công!",
        ERROR_VNPAY: "Không thể tạo mã QR",
        ERROR_CONN_VNPAY: "Lỗi kết nối khi tạo mã QR",
        SUCCESS_CASH: "Đã xác nhận giao dịch tiền mặt thành công!",
        ERROR_CASH: "Không thể xác nhận thanh toán",
        ERROR_CONN_CASH: "Lỗi kết nối khi xác nhận thanh toán",
        BOOK_DETAILS: "Chi tiết sách trả",
        LABEL_CODE: "Mã:",
        LABEL_STATUS: "Trạng thái:",
        LABEL_NOTE: "Ghi chú:",
        LABEL_FINE: "Phạt",
        COND_NORMAL: "Bình thường",
        COND_DAMAGED: "Hư hỏng",
        COND_LOST: "Mất sách",
        REFUND_AMOUNT: "Số tiền trả lại:",
        COLLECT_AMOUNT: "Số tiền thu thêm:",
        PAID_AMOUNT: "Đã thanh toán đủ:",
        WAITING_CONFIRMATION: "Đang chờ hệ thống xác nhận...",
    },
};
