export const ADMIN_BORROW_MANAGEMENT = {
    HEADER: {
        TITLE: "Lượt mượn",
        DESCRIPTION: "Quản lý danh sách mượn trả sách trong hệ thống",
        CREATE_BTN: "Tạo phiếu mượn mới",
    },
    FILTERS: {
        SEARCH_PLACEHOLDER: "Tìm theo tên thành viên, SĐT, Mã phiếu...",
        STATUS_ALL: "Trạng thái",
        STATUS_PENDING: "Chờ duyệt",
        STATUS_READY: "Chờ lấy",
        STATUS_BORROWED: "Đang mượn",
        STATUS_OVERDUE: "Quá hạn",
        STATUS_RETURNED: "Đã trả",
        DATE_SEPARATOR: "—",
        BTN_MORE_FILTER: "Lọc thêm",
        BTN_CLEAR_FILTER: "Bỏ lọc",
        BTN_APPLY_FILTER: "Lọc",
        LABEL_FROM: "Từ:",
        LABEL_TO: "Đến:",
        PAGINATION_PAGE: "Trang",
    },
    TABLE: {
        COL_MEMBER: "Thành viên",
        COL_BOOK: "Sách mượn",
        COL_BORROW_DATE: "Ngày mượn",
        COL_DUE_DATE: "Hạn trả",
        COL_STATUS: "Trạng thái",
        COL_ACTIONS: "Thao tác",
        BTN_VIEW: "Xem chi tiết",
        BTN_RETURN: "Xử lý trả sách",
        BTN_REMIND: "Gửi nhắc nhở",
        BTN_CONFIRM_HANDOVER: "Xác nhận giao sách",
        PAGINATION_INFO: "Hiển thị 1-3 trong số 124 lượt mượn",
        STATUS_BORROWED: "Đang mượn",
        STATUS_OVERDUE: "Quá hạn",
        STATUS_READY: "Chờ lấy",
        STATUS_RETURNED: "Đã trả",
        STATUS_PENDING: "Chờ duyệt",
        STATUS_PENDING_RENEWAL: "Chờ duyệt gia hạn",
        NO_DATE: "—",
        EMPTY_STATE: "Không có dữ liệu lượt mượn",
        GUEST_BADGE: "KHÁCH",
    },
    MODAL: {
        CREATE_TITLE: "Tạo phiếu mượn mới",
        BTN_CANCEL: "Hủy",
        BTN_CREATE: "Tạo phiếu mượn",
        CLOSE: "✕",
        LABEL_MEMBER_CODE: "Mã thành viên",
        PLACEHOLDER_MEMBER_CODE: "#MB-...",
        LABEL_BOOK_TITLE: "Tên sách",
        PLACEHOLDER_BOOK_TITLE: "Nhập tên sách...",
        LABEL_DUE_DATE: "Ngày hẹn trả",
        PLACEHOLDER_DUE_DATE: "dd/mm/yyyy",
        LABEL_PHONE: "Số điện thoại",
        LABEL_FULL_NAME: "Họ và tên",
        LABEL_EMAIL: "Email",
        LABEL_BOOK_BARCODE: "Mã vạch sách",
        HINT_OPTIONAL_CREATE: "(Tuỳ chọn nếu tạo mới)",
        HINT_OPTIONAL: "(Tuỳ chọn)",
        HINT_MULTIPLE_BARCODE: "Phân cách nhiều mã vạch bằng dấu phẩy (,)",
    },
    DETAIL_MODAL: {
        TITLE: "Chi tiết lượt mượn",
        ORDER_CODE: "Mã phiếu: ",
        SECTION_MEMBER: "Thông tin người mượn",
        MEMBER_NAME: "Họ tên:",
        MEMBER_CODE: "Mã thẻ/SĐT:",
        MEMBER_PHONE: "Số điện thoại:",
        SECTION_BORROW_INFO: "Thông tin mượn trả",
        CREATED_AT: "Ngày tạo:",
        DUE_DATE: "Ngày hẹn trả:",
        STATUS: "Trạng thái:",
        SECTION_BOOKS: "Danh sách sách mượn",
        BOOK_TITLE: "Tên sách",
        BOOK_AUTHOR: "Tác giả",
        BOOK_BARCODE: "Mã vạch",
        BOOK_STATUS: "Trạng thái",
        NO_BOOKS: "Không có dữ liệu sách",
        SECTION_FEE: "Chi phí",
        FEE_RENT: "Tiền thuê:",
        FEE_DISCOUNT: "Giảm giá:",
        FEE_DEPOSIT: "Tiền cọc:",
        FEE_TOTAL: "Tổng cộng:",
        GUEST_BADGE: "KHÁCH",
    },
};
