export const ADMIN = {
    SIDEBAR: {
        NAV_OVERVIEW: "Tổng quan",
        NAV_BOOKS: "Kho sách",
        NAV_CATEGORIES: "Thể loại",
        NAV_AUTHORS: "Tác giả",
        NAV_BORROWS: "Lượt mượn",
        NAV_REVIEWS: "Đánh giá",
        NAV_MEMBERS: "Thành viên",
        NAV_ROLES: "Vai trò & quyền",
        NAV_STATS: "Thống kê",
        NAV_SETTINGS: "Cài đặt",
        NAV_AUDIT_LOGS: "Nhật ký hệ thống",
        NAV_FINANCIALS: "Tài chính",
        ROLE_ADMIN: "Quản trị viên",
        SYS_NAME: "Hệ thống quản lý",
        BRAND_TITLE: "Library Admin",
        BRAND_SUBTITLE: "Illuminated Intelligence",
        HEADING_NAV: "Điều hướng",
        ADD_BOOK: "Thêm sách mới",
        SYSTEM_STATUS: "Trạng thái: Đang hoạt động",
        SUPPORT: "Hỗ trợ",
        LOGOUT: "Đăng xuất",
    },
    PENDING_REQUESTS: {
        TITLE: "Yêu cầu chờ duyệt",
        VIEW_ALL: "Xem tất cả",
        EMPTY_STATE: "Không còn yêu cầu nào đang chờ. Mọi thứ đã được xử lý.",
        TABLE_MEMBER: "Thành viên",
        TABLE_BOOK_TITLE: "Tựa sách yêu cầu",
        TABLE_MATCH: "Độ khớp",
        TABLE_ACTIONS: "Thao tác",
        BTN_REJECT: "Từ chối",
        BTN_APPROVE: "Duyệt",
    },
    SMART_CATALOGING: {
        TITLE: "Lên danh mục tự động",
        SUBTITLE: "Tải ảnh gáy sách hoặc mã ISBN — AI sẽ tự trích xuất thông tin.",
        DRAG_DROP: "Thả ảnh vào đây",
        OR_CLICK: "hoặc bấm để chọn tệp",
        MANUAL_ENTRY: "Nhập thủ công",
    },
    THONG_KE: {
        TITLE: "Thống kê",
        DESCRIPTION: "Trang thống kê sẽ chứa biểu đồ và số liệu tại đây.",
    },
    MODAL: {
        ADD_BOOK: {
            TITLE: "Thêm Sách Mới",
            TITLE_INPUT: "Tiêu đề *",
            AUTHOR_INPUT: "Tác giả *",
            ISBN_INPUT: "ISBN",
            CATEGORY_INPUT: "Thể loại",
            PUBLISHER_INPUT: "Nhà xuất bản",
            PUBLICATION_DATE_INPUT: "Ngày xuất bản",
            PAGES_INPUT: "Số trang",
            DESCRIPTION_INPUT: "Mô tả sách",
            SHELF_LOCATION_INPUT: "Vị trí kệ sách",
            IMAGE_URL_INPUT: "URL Ảnh bìa",
            DEPOSIT_PRICE_INPUT: "Giá cọc",
            CANCEL: "Hủy bỏ",
            SUBMIT: "Thêm sách",
            SUCCESS: "Thêm sách thành công!",
            ERROR: "Lỗi khi thêm sách",
            LOADING: "Đang xử lý...",
            SELECT_AUTHOR_PLACEHOLDER: "Chọn hoặc nhập tác giả mới...",
            CREATE_AUTHOR: "Tạo tác giả",
            NO_AUTHOR_FOUND: "Không tìm thấy tác giả",
            SELECT_CATEGORY_PLACEHOLDER: "Chọn hoặc nhập thể loại mới...",
            CREATE_CATEGORY: "Tạo thể loại",
            NO_CATEGORY_FOUND: "Không tìm thấy thể loại",
        },
        EDIT_BOOK: {
            TITLE: "Chỉnh sửa sách",
            TITLE_INPUT: "Tiêu đề *",
            AUTHOR_INPUT: "Tác giả *",
            ISBN_INPUT: "ISBN",
            CATEGORY_INPUT: "Thể loại",
            QUANTITY_TOTAL: "Tổng số lượng",
            QUANTITY_AUTO_NOTE: "Tự động cập nhật từ danh sách bản sao",
            QUANTITY_AVAILABLE: "Số lượng có sẵn",
            SHELF_LOCATION_INPUT: "Vị trí kệ sách",
            IMAGE_URL_INPUT: "URL Ảnh bìa",
            CANCEL: "Hủy bỏ",
            SUBMIT: "Lưu thay đổi",
            SUCCESS: "Cập nhật sách thành công!",
            ERROR: "Lỗi khi lưu sách",
            LOADING: "Đang xử lý...",
            SELECT_AUTHOR_PLACEHOLDER: "Chọn hoặc nhập tác giả mới...",
            CREATE_AUTHOR: "Tạo tác giả",
            NO_AUTHOR_FOUND: "Không tìm thấy tác giả",
            SELECT_CATEGORY_PLACEHOLDER: "Chọn hoặc nhập thể loại mới...",
            CREATE_CATEGORY: "Tạo thể loại",
            NO_CATEGORY_FOUND: "Không tìm thấy thể loại",
        },
        DELETE_AUTHOR: {
            TITLE: "Xác nhận xoá tác giả",
            DESCRIPTION:
                "Bạn có chắc chắn muốn xoá tác giả này? Các sách thuộc tác giả này sẽ không còn hiển thị tác giả này nữa. Hành động này không thể hoàn tác.",
            CANCEL: "Hủy",
            CONFIRM: "Xóa tác giả",
        },
        BOOK_COPIES: {
            TITLE: "Quản lý các cuốn sách (Bản sao)",
            BOOK_TITLE: "Đầu sách:",
            TOTAL: "Tổng cộng:",
            COPIES_UNIT: "cuốn",
            ADD_COPY: "Thêm cuốn",
            EMPTY_STATE: "Chưa có cuốn sách (bản sao) nào cho đầu sách này.",
            IMPORT_NOW: "Nhập kho ngay",
            COL_BARCODE: "Mã Vạch (Barcode)",
            COL_STATUS: "Trạng Thái",
            COL_CONDITION_NOTE: "Ghi chú tình trạng",
            COL_ACTIONS: "Thao tác",
            NO_NOTE: "Không có",
            STATUS_AVAILABLE: "Sẵn sàng",
            STATUS_BORROWED: "Đang mượn",
            STATUS_LOST: "Bị mất",
            STATUS_DAMAGED: "Hư hỏng",
            STATUS_MAINTENANCE: "Bảo trì",
            ERROR_FETCH: "Lỗi khi tải danh sách bản sao",
            ERROR_ADD: "Lỗi khi thêm bản sao",
            ERROR_UPDATE: "Lỗi khi cập nhật trạng thái",
            CONFIRM_DELETE: "Bạn có chắc chắn muốn xoá bản sao này? Hành động này không thể hoàn tác.",
            ERROR_DELETE: "Lỗi khi xoá bản sao",
            LOADING_DATA: "Đang tải dữ liệu...",
            TOOLTIP_DELETE: "Xoá bản sao này",
        },
    },
};
