export const ADMIN_INVENTORY_MANAGEMENT = {
    FILTERS: {
        CATEGORY_ALL: "Thể loại: Tất cả",
    },
    TABLE: {
        NOT_UPDATED: "Chưa cập nhật",
        NA: "N/A",
        BTN_COPIES: "Chi tiết các cuốn",
        BTN_EDIT: "Sửa thông tin",
        BTN_DELETE: "Xóa",
        DELETE_CONFIRM: "Bạn có chắc chắn muốn xóa sách này? Sách sẽ được ẩn khỏi kho và danh mục.",
        DELETE_DIALOG_TITLE: "Xóa sách khỏi kho?",
        DELETE_DIALOG_DESCRIPTION: "Sách sẽ được ẩn khỏi kho và danh mục công khai. Bạn vẫn có thể giữ lại dữ liệu lịch sử liên quan.",
        DELETE_DIALOG_BOOK_LABEL: "Sách được chọn",
        DELETE_DIALOG_CLOSE: "Đóng hộp thoại xóa sách",
        DELETE_DIALOG_CANCEL: "Giữ lại",
        DELETE_DIALOG_CONFIRM: "Xóa sách",
        DELETE_DIALOG_DELETING: "Đang xóa...",
        DELETE_SUCCESS: "Đã xóa sách thành công",
        DELETE_ERROR: "Không thể xóa sách. Vui lòng thử lại.",
        COL_COVER: "Ảnh bìa",
        COL_TITLE: "Tiêu đề & Tác giả",
        COL_ISBN: "ISBN-13",
        COL_CATEGORY: "Thể loại",
        COL_STOCK: "Tồn kho",
        COL_LOCATION: "Vị trí",
        COL_ACTIONS: "Thao tác",
        EMPTY_STATE: "Không tìm thấy sách nào phù hợp với bộ lọc.",
    },
};
