export const ADMIN_PAGES = {
    DASHBOARD: {
        TITLE: "Tổng quan",
        DESCRIPTION: "Theo dõi nhanh sức khỏe vận hành thư viện trong ngày.",
        UPDATED_LABEL: "Dữ liệu hiện tại",
        BOOKS_TODAY: "Sách mượn hôm nay",
        BOOKS_TODAY_DESC: "Số lượt mượn phát sinh trong ngày.",
        PENDING_APPROVAL: "Chờ phê duyệt",
        PENDING_APPROVAL_DESC: "Yêu cầu mượn đang cần thủ thư xử lý.",
        OVERDUE_BOOKS: "Sách quá hạn",
        OVERDUE_BOOKS_DESC: "Phiếu mượn đã vượt hạn trả dự kiến.",
        TOTAL_BOOKS: "Tổng đầu sách",
        TOTAL_BOOKS_DESC: "Tổng số đầu sách đang được quản lý.",
        AVAILABLE_BOOKS: "Sách khả dụng",
        AVAILABLE_BOOKS_DESC: "Bản sao sẵn sàng để độc giả mượn.",
        READERS: "Độc giả",
        READERS_DESC: "Tổng số độc giả đã đăng ký trong hệ thống.",
        TREND_TITLE: "Xu hướng mượn trả",
        TREND_DESC: "Tổng hợp theo tháng từ dữ liệu mượn, trả và quá hạn.",
        TREND_BORROWED: "Mượn",
        TREND_RETURNED: "Trả",
        TREND_OVERDUE: "Quá hạn",
        ATTENTION_TITLE: "Cần chú ý",
        ATTENTION_DESC: "Các tín hiệu nên được xử lý trước trong ca vận hành.",
        ATTENTION_PENDING: "Duyệt yêu cầu mượn",
        ATTENTION_OVERDUE: "Theo dõi sách quá hạn",
        ATTENTION_AVAILABLE: "Tỷ lệ sách khả dụng",
        RECENT_TITLE: "Hoạt động gần đây",
        RECENT_EMPTY: "Chưa có hoạt động mượn trả gần đây.",
        TOP_BOOKS_TITLE: "Sách được mượn nhiều",
        TOP_CATEGORIES_TITLE: "Thể loại nổi bật",
        EMPTY_LIST: "Chưa có dữ liệu để hiển thị.",
        ERROR_TITLE: "Không thể tải dashboard",
        ERROR_DESC: "Vui lòng kiểm tra kết nối hoặc thử tải lại dữ liệu.",
        RETRY: "Tải lại",
    },
    MEMBERS: {
        TITLE: "Thành viên",
        DESC: "Trang quản lý thành viên thư viện sẽ hiển thị ở đây.",
    },
    BORROW_LOGS: {
        TITLE: "Lượt mượn",
        DESC: "Trang quản lý lượt mượn sách sẽ hiển thị thông tin ở đây.",
    },
    INVENTORY: {
        TITLE: "Kho sách",
        DESC: "Đây là trang kho sách. Bạn có thể thêm nội dung quản lý sách ở đây.",
        PAGE_DESC: "Quản lý các mục trong danh mục, giám sát tình trạng có sẵn và tận dụng tính năng quét AI để nhập liệu nhanh chóng.",
        AI_OCR_BTN: "AI OCR",
    },
    SETTINGS: {
        TITLE: "Cài đặt",
        DESC: "Trang cài đặt của hệ thống quản lý thư viện.",
    },
    ROLES: {
        TITLE: "Vai trò & quyền",
        DESC: "Quản lý quyền hạn truy cập của nhân viên.",
    },
};
