export const ADMIN_REVIEWS = {
    BREADCRUMB_LABEL: "Đánh giá & bình luận",
    PAGE_TITLE: "Quản lý đánh giá & bình luận",
    PAGE_DESCRIPTION: "Kiểm duyệt các phản hồi từ người dùng trên hệ thống thư viện.",
    SEARCH_PLACEHOLDER: "Tìm kiếm đánh giá, người dùng, sách...",
    NOTIFICATIONS_LABEL: "Thông báo kiểm duyệt",
    APP_SWITCHER_LABEL: "Mở lưới công cụ",
    HIDE_REASON_LABEL: "Lý do ẩn",
    HIDE_REASON_PLACEHOLDER: "Nhập lý do...",
    HIDE_REASON_DIALOG_DESCRIPTION: "Chọn lý do để ẩn đánh giá này khỏi hệ thống.",
    CUSTOM_HIDE_REASON: "Khác...",
    HIDE_REASON_OPTIONS: ["Spam", "Ngôn từ không phù hợp", "Tiết lộ nội dung", "Không liên quan đến sách"],
    DETAIL: "Chi tiết",
    HIDE: "Ẩn",
    RESTORE: "Khôi phục",
    DELETE: "Xóa",
    CONFIRM: "Xác nhận",
    CANCEL: "Hủy",
    REVIEW_FOR: "Đánh giá cho",
    HIDDEN_BY_ADMIN: "Ẩn bởi Admin",
    REASON: "Lý do",
    EMPTY_STATE: "Không có đánh giá phù hợp với bộ lọc hiện tại.",
    STATS: {
        TOTAL: "Tổng phản hồi",
        REPORTED: "Bị báo cáo",
        HIDDEN: "Đã ẩn",
    },
    CONTROLS: {
        FILTER_TITLE: "Lọc theo",
        FILTER_LABEL: "Nhóm đánh giá",
        SEARCH_LABEL: "Tìm kiếm đánh giá",
        CLEAR_SEARCH: "Xóa tìm kiếm",
    },
    PAGINATION: {
        PAGE_LABEL: "Trang",
        PREVIOUS_PAGE: "Trang trước",
        NEXT_PAGE: "Trang sau",
    },
    FILTERS: {
        ALL: "Tất cả",
        REPORTED: "Bị báo cáo",
        RECENT: "Gần đây",
        RATING_5: "5",
        RATING_4: "4",
        RATING_3: "3",
        RATING_2: "2",
        RATING_1: "1",
        HIDDEN: "Đã ẩn",
    },
    STATUS: {
        REPORTED: "Bị báo cáo",
        HIDDEN: "Đã ẩn",
        VISIBLE: "Đang hiển thị",
    },
    SAMPLE_REVIEWS: [
        {
            id: "review-001",
            reviewerName: "Nguyễn Văn A",
            reviewerInitials: "NA",
            reviewerRole: "Độc giả",
            bookTitle: "Dế Mèn Phiêu Lưu Ký",
            rating: 2,
            createdAt: "15 phút trước",
            createdDaysAgo: 0,
            content: "Sách rất hay, nhưng có vài chỗ cần cải thiện...",
            status: "reported",
            hideReason: "",
            accent: "warning",
        },
        {
            id: "review-002",
            reviewerName: "Lê Thị B",
            reviewerInitials: "LB",
            reviewerRole: "Thành viên",
            bookTitle: "Nhà Giả Kim",
            rating: 5,
            createdAt: "1 ngày trước",
            createdDaysAgo: 1,
            content: "Tuyệt vời!",
            status: "visible",
            hideReason: "",
            accent: "secondary",
        },
        {
            id: "review-003",
            reviewerName: "Trần Văn C",
            reviewerInitials: "TC",
            reviewerRole: "Độc giả",
            bookTitle: "Tư Duy Nhanh Và Chậm",
            rating: 2,
            createdAt: "2 ngày trước",
            createdDaysAgo: 2,
            content: "Bình thường.",
            status: "hidden",
            hideReason: "Spam",
            accent: "muted",
        },
        {
            id: "review-004",
            reviewerName: "Phạm Minh D",
            reviewerInitials: "PD",
            reviewerRole: "Thành viên",
            bookTitle: "Không Gia Đình",
            rating: 4,
            createdAt: "4 ngày trước",
            createdDaysAgo: 4,
            content: "Nội dung cảm động, bản in rõ và dễ đọc.",
            status: "visible",
            hideReason: "",
            accent: "primary",
        },
    ],
} as const;
