export const ADMIN_SETTINGS = {
    TOPBAR_TITLE: "Admin Portal",
    PAGE_TITLE: "Chính sách nghiệp vụ",
    PAGE_DESCRIPTION: "Cấu hình tham số vận hành cốt lõi, ưu tiên khu vực và các tính năng toàn hệ thống cho nền tảng thư viện.",
    BORROWING: {
        TITLE: "Chính sách mượn sách",
        MAX_DAYS: "Số ngày mượn tối đa",
        FINE_PER_DAY: "Phạt mỗi ngày (VND)",
        MAX_BOOKS: "Số sách mượn đồng thời",
        DEPOSIT_PERCENTAGE: "Tỷ lệ đặt cọc",
        MAX_RENEWALS: "Số lần gia hạn tối đa",
        RENEWALS_HELP: "Số lần độc giả có thể gia hạn một lượt mượn trước khi trả sách.",
    },
    PAYMENTS: {
        TITLE: "Cổng thanh toán",
        ACTIVE: "Đang bật",
        INACTIVE: "Tạm tắt",
        VERIFIED: "Đã xác thực",
        NEEDS_CONNECTION: "Cần kết nối",
        MANAGE_CONNECTION: "Quản lý kết nối",
        CONNECT_GATEWAY: "Kết nối cổng",
        TOKEN_LABEL: "Mã kết nối",
        MOMO_TOKEN: "MOMO-LIVE-24",
        VNPAY_TOKEN: "CHƯA CẤP",
        MOMO_NAME: "MoMo Wallet",
        MOMO_DESC: "Tích hợp ví điện tử trực tiếp",
        MOMO_NOTE: "Sẵn sàng nhận tiền cọc và tiền phạt qua ví MoMo.",
        VNPAY_NAME: "VNPay",
        VNPAY_DESC: "Tích hợp chuyển khoản ngân hàng & QR",
        VNPAY_NOTE: "Cần nhập TmnCode, HashSecret và URL callback trước khi bật.",
    },
    FEATURES: {
        TITLE: "Tính năng hệ thống",
        AI_SEARCH_TITLE: "AI Semantic Search",
        AI_SEARCH_DESC: "Bật xử lý ngôn ngữ tự nhiên cho tìm kiếm danh mục công khai. Có thể tăng mức sử dụng API.",
        ONLINE_PAYMENTS_TITLE: "Thanh toán trực tuyến",
        ONLINE_PAYMENTS_DESC: "Cho phép độc giả thanh toán tiền phạt và tiền cọc qua các cổng đã tích hợp.",
        AUTO_BACKUP_TITLE: "Sao lưu tự động hằng ngày",
        AUTO_BACKUP_DESC: "Tự động tạo snapshot cơ sở dữ liệu lúc 02:00 theo giờ hệ thống.",
    },
    LOCALIZATION: {
        TITLE: "Bản địa hóa",
        LANGUAGE: "Ngôn ngữ",
        WORLD_CLOCK: "Đồng hồ thế giới",
        TIMEZONE: "Múi giờ hệ thống",
        VIETNAMESE: "Tiếng Việt (VN)",
        ENGLISH: "English (US)",
        BANGKOK_HANOI: "(UTC+07:00) Bangkok, Hà Nội, Jakarta",
        UTC: "UTC",
    },
    ACTION_BAR: {
        WARNING: "Các thay đổi chưa lưu sẽ bị mất nếu bạn rời trang này.",
        DISCARD: "Hủy bỏ",
        SAVE: "Lưu thay đổi",
        SUCCESS: "Cài đặt hệ thống đã được lưu thành công.",
        DISCARD_CONFIRM_TITLE: "Hủy thay đổi?",
        DISCARD_CONFIRM_MESSAGE: "Các thay đổi chưa lưu trên trang cài đặt sẽ bị mất. Bạn muốn tiếp tục chỉnh sửa hay hủy toàn bộ thay đổi?",
        KEEP_EDITING: "Tiếp tục chỉnh sửa",
        CONFIRM_DISCARD: "Hủy thay đổi",
    },
};
