export const ADMIN_SETTINGS = {
    TOPBAR_TITLE: "Admin Portal",
    PAGE_TITLE: "Chính sách nghiệp vụ",
    PAGE_DESCRIPTION: "Cấu hình tham số vận hành cốt lõi, ưu tiên khu vực và các tính năng toàn hệ thống cho nền tảng thư viện.",
    BORROWING: {
        TITLE: "Chính sách mượn sách",
        MAX_DAYS: "Số ngày mượn tối đa",
        FINE_PER_DAY: "Phạt mỗi ngày (VND)",
        MAX_BOOKS: "Số sách mượn đồng thời",
        DEPOSIT_PERCENTAGE: "Tỷ lệ đặt cọc",
        MAX_RENEWALS: "Số lần gia hạn tối đa",
        RENEWALS_HELP: "Số lần độc giả có thể gia hạn một lượt mượn trước khi trả sách.",
    },
    PAYMENTS: {
        TITLE: "Cổng thanh toán",
        ACTIVE: "Đang bật",
        INACTIVE: "Tạm tắt",
        VERIFIED: "Đã xác thực",
        NEEDS_CONNECTION: "Cần kết nối",
        MANAGE_CONNECTION: "Quản lý kết nối",
        CONNECT_GATEWAY: "Kết nối cổng",
        TOKEN_LABEL: "Mã kết nối",
        MOMO_TOKEN: "MOMO-LIVE-24",
        VNPAY_TOKEN: "CHƯA CẤP",
        MOMO_NAME: "MoMo Wallet",
        MOMO_DESC: "Tích hợp ví điện tử trực tiếp",
        MOMO_NOTE: "Sẵn sàng nhận tiền cọc và tiền phạt qua ví MoMo.",
        VNPAY_NAME: "VNPay",
        VNPAY_DESC: "Tích hợp chuyển khoản ngân hàng & QR",
        VNPAY_NOTE: "Cần nhập TmnCode, HashSecret và URL callback trước khi bật.",
        VNPAY_CONFIG_TITLE: "Cấu hình VNPay",
        VNPAY_CONFIG_TMN_CODE: "TmnCode",
        VNPAY_CONFIG_HASH_SECRET: "HashSecret",
        VNPAY_CONFIG_ACTIVE: "Kích hoạt cổng thanh toán",
    },
    FEATURES: {
        TITLE: "Tính năng hệ thống",
        AI_SEARCH_TITLE: "AI Semantic Search",
        AI_SEARCH_DESC: "Bật xử lý ngôn ngữ tự nhiên cho tìm kiếm danh mục công khai. Có thể tăng mức sử dụng API.",
        ONLINE_PAYMENTS_TITLE: "Thanh toán trực tuyến",
        ONLINE_PAYMENTS_DESC: "Cho phép độc giả thanh toán tiền phạt và tiền cọc qua các cổng đã tích hợp.",
        AUTO_BACKUP_TITLE: "Sao lưu tự động hằng ngày",
        AUTO_BACKUP_DESC: "Tự động tạo snapshot cơ sở dữ liệu lúc 02:00 theo giờ hệ thống.",
    },
    LOCALIZATION: {
        TITLE: "Bản địa hóa",
        LANGUAGE: "Ngôn ngữ",
        WORLD_CLOCK: "Đồng hồ thế giới",
        TIMEZONE: "Múi giờ hệ thống",
        VIETNAMESE: "Tiếng Việt (VN)",
        ENGLISH: "English (US)",
        BANGKOK_HANOI: "(UTC+07:00) Bangkok, Hà Nội, Jakarta",
        UTC: "UTC",
        LANGUAGES: {
            ZH: "中文 (简体)",
            HI: "हिन्दी (IN)",
            ES: "Español (ES)",
            FR: "Français (FR)",
            AR: "العربية",
            BN: "বাংলা (BD)",
            PT: "Português (BR)",
            RU: "Русский (RU)",
            JA: "日本語 (JP)",
        },
        TIMEZONES: {
            UTC_MINUS_12: "(UTC-12:00) Baker Island, Howland Island",
            UTC_MINUS_11: "(UTC-11:00) Pago Pago, Niue",
            UTC_MINUS_10: "(UTC-10:00) Honolulu, Papeete",
            UTC_MINUS_9: "(UTC-09:00) Anchorage, Juneau",
            UTC_MINUS_8: "(UTC-08:00) Los Angeles, Vancouver, San Francisco",
            UTC_MINUS_7: "(UTC-07:00) Denver, Phoenix, Calgary",
            UTC_MINUS_6: "(UTC-06:00) Chicago, Mexico City, Guatemala City",
            UTC_MINUS_5: "(UTC-05:00) New York, Toronto, Lima, Bogota",
            UTC_MINUS_4: "(UTC-04:00) Santiago, Caracas, La Paz",
            UTC_MINUS_3: "(UTC-03:00) Buenos Aires, Sao Paulo, Montevideo",
            UTC_MINUS_2: "(UTC-02:00) South Georgia, Fernando de Noronha",
            UTC_MINUS_1: "(UTC-01:00) Azores, Cape Verde",
            UTC_PLUS_0: "(UTC+00:00) London, Lisbon, Accra, Reykjavik",
            UTC_PLUS_1: "(UTC+01:00) Paris, Berlin, Rome, Madrid",
            UTC_PLUS_2: "(UTC+02:00) Athens, Cairo, Johannesburg, Helsinki",
            UTC_PLUS_3: "(UTC+03:00) Moscow, Istanbul, Riyadh, Nairobi",
            UTC_PLUS_4: "(UTC+04:00) Dubai, Abu Dhabi, Baku, Muscat",
            UTC_PLUS_5: "(UTC+05:00) Karachi, Tashkent, Yekaterinburg",
            UTC_PLUS_6: "(UTC+06:00) Dhaka, Almaty, Bishkek",
            UTC_PLUS_7: "(UTC+07:00) Hà Nội, Bangkok, Jakarta, Phnom Penh",
            UTC_PLUS_8: "(UTC+08:00) Singapore, Beijing, Hong Kong, Kuala Lumpur",
            UTC_PLUS_9: "(UTC+09:00) Tokyo, Seoul, Pyongyang",
            UTC_PLUS_10: "(UTC+10:00) Sydney, Melbourne, Brisbane, Port Moresby",
            UTC_PLUS_11: "(UTC+11:00) Nouméa, Honiara, Magadan",
            UTC_PLUS_12: "(UTC+12:00) Auckland, Wellington, Suva",
            UTC_PLUS_13: "(UTC+13:00) Apia, NukuÊ»alofa, Fakaofo",
            UTC_PLUS_14: "(UTC+14:00) Kiritimati / Christmas Island, Line Islands",
        },
    },
    ACTION_BAR: {
        WARNING: "Các thay đổi chưa lưu sẽ bị mất nếu bạn rời trang này.",
        DISCARD: "Hủy bỏ",
        SAVE: "Lưu thay đổi",
        SUCCESS: "Cài đặt hệ thống đã được lưu thành công.",
        DISCARD_CONFIRM_TITLE: "Hủy thay đổi?",
        DISCARD_CONFIRM_MESSAGE: "Các thay đổi chưa lưu trên trang cài đặt sẽ bị mất. Bạn muốn tiếp tục chỉnh sửa hay hủy toàn bộ thay đổi?",
        KEEP_EDITING: "Tiếp tục chỉnh sửa",
        CONFIRM_DISCARD: "Hủy thay đổi",
        CANCEL: "Hủy",
    },
};
