export const ADMIN_UI = {
    AUTHORS: { ADD_SUCCESS: "", ADD_FAILED: "", TITLE: "Tác giả", DESC: "Quản lý" },
    CATEGORIES: { ADD_SUCCESS: "", ADD_FAILED: "", EDIT_SUCCESS: "", EDIT_FAILED: "", NO_DESC: "", TITLE: "Thể loại", DESC: "Quản lý", DELETE_BTN: "Xóa" },
    BOOKS: {
        ADD_SUCCESS: "",
        ADD_FAILED: "",
        EDIT_SUCCESS: "",
        EDIT_FAILED: "",
        ADD_BTN: "",
        SEARCH_PLACEHOLDER: "",
        TABLE_TITLE: "",
        VIEW_DETAIL: "",
        EMPTY_STATE: "",
        NOT_SHELVED: "Chưa xếp giá",
        SHOWING: "Hiển thị",
        TO: "đến",
        OF: "của",
        ITEMS: "mục",
    },
    USERS: { EDIT_SUCCESS: "", EDIT_FAILED: "", ROLE_USER: "", ROLE_ADMIN: "", EDIT_TITLE: "Sửa", SAVING: "Đang lưu...", SAVE_CHANGES: "Lưu thay đổi" },
    BORROW: { RENEW_SUCCESS: "", RENEW_FAILED: "", RETURN_SUCCESS: "", RETURN_FAILED: "", PENDING_RENEWAL: "Chờ duyệt" },
    ANALYTICS: {
        TOTAL_USERS: "",
        ACTIVE_USERS: "",
        TOTAL_BOOKS: "",
        BORROWED_BOOKS: "",
        REVENUE: "",
        GROWTH: "",
        AVAILABLE_BOOKS: "",
        OVERDUE_BOOKS: "",
        READERS: "",
        REQUESTS: "",
    },

    USER_MODAL: {
        CONFIRM_BAN: "Bạn có chắc chắn muốn khóa tài khoản này?",
        CONFIRM_BAN_DESC: "Tài khoản này sẽ không thể đăng nhập hoặc mượn sách được nữa.",
        BAN_ACCOUNT: "Khóa tài khoản",
        UPDATE_SUCCESS: "Cập nhật thành công",
        UPDATE_FAILED: "Cập nhật thất bại",
    },
    SETTINGS: {
        CURRENCY_SUFFIX: "đ",
        NOTIFICATIONS: "Thông báo",
        SECURITY: "Bảo mật",
        SYSTEM: "Hệ thống",
        LANG_PT_BR: "Tiếng Bồ Đào Nha",
        TIMEZONE_HAN: "Hà Nội",
        TIMEZONE_NOU: "Noumea",
    },
};

export const AUDIT_MOCK = [
    { actor: "Nguyễn An (Quản trị viên)", description: "Quản trị viên cập nhật chính sách giới hạn tần suất truy cập API.", ipAddress: "192.168.1.45" },
    { actor: "Hệ thống tự động", description: "Tác vụ đồng bộ dữ liệu danh mục bên ngoài kết thúc với trạng thái thất bại.", ipAddress: "10.0.0.22 (Nội bộ)" },
    { actor: "Trần Minh (Người dùng)", description: "Người dùng tạo bản ghi biên mục mới trong kho dữ liệu.", ipAddress: "203.0.113.88" },
    { actor: "Nguồn không xác định", description: "Hệ thống chặn yêu cầu xác thực bất thường vào điểm cuối quản trị.", ipAddress: "198.51.100.14" },
    { actor: "Nguyễn An (Quản trị viên)", description: "Quản trị viên đăng nhập và hệ thống tạo phiên làm việc mới.", ipAddress: "192.168.1.45" },
    { actor: "Hệ thống tự động", description: "Hệ thống tạo báo cáo thống kê sử dụng theo tuần.", ipAddress: "10.0.0.5 (Nội bộ)" },
    { actor: "Lê Hương (Người dùng)", description: "Người dùng cập nhật thông tin hồ sơ độc giả.", ipAddress: "203.0.113.41" },
    { actor: "Hệ thống tự động", description: "Hệ thống tạo snapshot sao lưu dữ liệu định kỳ.", ipAddress: "10.0.0.8 (Nội bộ)" },
    { actor: "Phạm Khoa (Người dùng)", description: "Người dùng gia hạn lượt mượn nhưng không đáp ứng điều kiện nghiệp vụ.", ipAddress: "198.51.100.21" },
    { actor: "Mai Linh (Người dùng)", description: "Người dùng tạo yêu cầu đặt mượn sách từ danh mục trực tuyến.", ipAddress: "192.0.2.73" },
];
