export const ADMIN_USER_MANAGEMENT = {
    HEADER: {
        TITLE: "Users",
        DESCRIPTION: "Manage library access, roles, and user accounts.",
        CREATE_BTN: "+ Create User",
    },
    FILTERS: {
        SEARCH_PLACEHOLDER: "Search by name, email, or ID...",
        ROLES: {
            ALL: "All Roles",
            ADMIN: "Admin",
            LIBRARIAN: "Librarian",
            CUSTOMER: "Customer",
        },
        STATUS: {
            ALL: "All Status",
            ACTIVE: "Active",
            LOCKED: "Locked",
            INACTIVE: "Inactive",
        },
        RELOAD: "🔄 Reload",
    },
    TABLE: {
        COL_USER: "User",
        COL_EMAIL: "Email",
        COL_ROLE: "Role",
        COL_STATUS: "Status",
        COL_LAST_LOGIN: "Last Login",
        COL_ACTIONS: "Actions",
        BTN_EDIT: "Edit",
        BTN_LOCK: "Lock",
        BTN_UNLOCK: "Unlock",
        PAGINATION: {
            SHOWING: "Hiển thị",
            TO: "-",
            OF: "trong số",
            ITEMS: "thành viên",
        },
        EMPTY_STATE: "Không có dữ liệu thành viên",
    },
    MODAL: {
        CREATE_TITLE: "Create User",
        EDIT_TITLE: "Edit User",
        PLACEHOLDER_NAME: "Full Name",
        PLACEHOLDER_EMAIL: "Email",
        PLACEHOLDER_LAST_LOGIN: "Last Login",
        BTN_CANCEL: "Cancel",
        BTN_CREATE: "Create",
        BTN_SAVE: "Save",
        CLOSE: "✕",
        HINT_EMAIL_EDIT: "Không thể thay đổi email sau khi đăng ký.",
        LABEL_PASSWORD: "Mật khẩu khởi tạo",
        HINT_ROLE_ADMIN_EDIT: "Không thể thay đổi vai trò của tài khoản Admin.",
        HINT_ROLE_ADMIN_CREATE: "Không thể cấp quyền Admin cho tài khoản mới.",
    },
};
