export const ADMIN_USER_MANAGEMENT = {
    HEADER: {
        TITLE: "Thành viên",
        DESCRIPTION: "Quản lý quyền truy cập, vai trò và tài khoản người dùng thư viện.",
        CREATE_BTN: "+ Tạo tài khoản",
    },
    FILTERS: {
        SEARCH_PLACEHOLDER: "Tìm theo tên, email hoặc mã...",
        ROLES: {
            ALL: "Tất cả vai trò",
            ADMIN: "Admin",
            LIBRARIAN: "Thủ thư",
            CUSTOMER: "Độc giả",
        },
        STATUS: {
            ALL: "Tất cả trạng thái",
            ACTIVE: "Đang hoạt động",
            LOCKED: "Đã khóa",
            INACTIVE: "Chưa kích hoạt",
        },
        RELOAD: "Tải lại",
    },
    TABLE: {
        COL_USER: "Người dùng",
        COL_EMAIL: "Email",
        COL_ROLE: "Vai trò",
        COL_STATUS: "Trạng thái",
        COL_LAST_LOGIN: "Lần đăng nhập cuối",
        COL_ACTIONS: "Thao tác",
        BTN_EDIT: "Sửa",
        BTN_LOCK: "Khóa",
        BTN_UNLOCK: "Mở khóa",
        PAGINATION: {
            SHOWING: "Hiển thị",
            TO: "-",
            OF: "trong số",
            ITEMS: "thành viên",
        },
        EMPTY_STATE: "Không có dữ liệu thành viên",
    },
    MODAL: {
        CREATE_TITLE: "Tạo tài khoản",
        EDIT_TITLE: "Chỉnh sửa tài khoản",
        PLACEHOLDER_NAME: "Họ và tên",
        PLACEHOLDER_EMAIL: "Email",
        PLACEHOLDER_LAST_LOGIN: "Lần đăng nhập cuối",
        BTN_CANCEL: "Hủy",
        BTN_CREATE: "Tạo",
        BTN_SAVE: "Lưu",
        CLOSE: "✕",
        HINT_EMAIL_EDIT: "Không thể thay đổi email sau khi đăng ký.",
        LABEL_PASSWORD: "Mật khẩu khởi tạo",
        HINT_ROLE_ADMIN_EDIT: "Không thể thay đổi vai trò của tài khoản Admin.",
        HINT_ROLE_ADMIN_CREATE: "Không thể cấp quyền Admin cho tài khoản mới.",
    },
};
