import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#c6e7ff",
        "on-primary": "#ffffff",
        "on-surface": "#191c1d",
        "on-secondary-container": "#004866",
        "on-background": "#191c1d",
        "on-surface-variant": "#464652",
        secondary: "#00658d",
        "on-secondary-fixed-variant": "#004c6b",
        "on-primary-container": "#9da1ff",
        "inverse-on-surface": "#f0f1f2",
        "on-tertiary-fixed-variant": "#6700b5",
        "on-primary-fixed-variant": "#373a9b",
        "secondary-container": "#2dbcfe",
        "on-tertiary": "#ffffff",
        "inverse-primary": "#c0c1ff",
        "surface-dim": "#d9dadb",
        "surface-container-highest": "#e1e3e4",
        "surface-container": "#edeeef",
        primary: "#15157d",
        "tertiary-container": "#5c00a2",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        background: "#f8f9fa",
        "tertiary-fixed": "#efdbff",
        outline: "#777683",
        "secondary-fixed-dim": "#82cfff",
        "on-error": "#ffffff",
        "surface-container-high": "#e7e8e9",
        "primary-container": "#2e3192",
        "outline-variant": "#c7c5d4",
        "inverse-surface": "#2e3132",
        error: "#ba1a1a",
        "surface-variant": "#e1e3e4",
        "surface-tint": "#4f54b4",
        "tertiary-fixed-dim": "#dcb8ff",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#001e2d",
        "on-tertiary-fixed": "#2c0051",
        "on-primary-fixed": "#04006d",
        tertiary: "#3e0070",
        surface: "#f8f9fa",
        "primary-fixed": "#e1e0ff",
        "on-tertiary-container": "#c792ff",
        "on-error-container": "#93000a",
        "surface-container-low": "#f3f4f5",
        "primary-fixed-dim": "#c0c1ff",
        "surface-bright": "#f8f9fa",
      },
    },
  },
  plugins: [],
};

export default config;
