export const ADMIN = {
    SIDEBAR: {
        NAV_OVERVIEW: "Tổng quan",
        NAV_BOOKS: "Kho sách",
        NAV_BORROWS: "Lượt mượn",
        NAV_MEMBERS: "Thành viên",
        NAV_ROLES: "Vai trò & quyền",
        NAV_STATS: "Thống kê",
        NAV_SETTINGS: "Cài đặt",
        NAV_AUDIT_LOGS: "Nhật ký hệ thống",
        NAV_FINANCIALS: "Tài chính",
        ROLE_ADMIN: "Quản trị viên",
        SYS_NAME: "Hệ thống quản lý",
        BRAND_TITLE: "Library Admin",
        BRAND_SUBTITLE: "Illuminated Intelligence",
        HEADING_NAV: "Điều hướng",
        ADD_BOOK: "Thêm sách mới",
        SYSTEM_STATUS: "Trạng thái: Đang hoạt động",
        SUPPORT: "Hỗ trợ",
        LOGOUT: "Đăng xuất",
    },
    PENDING_REQUESTS: {
        TITLE: "Yêu cầu chờ duyệt",
        VIEW_ALL: "Xem tất cả",
        EMPTY_STATE: "Không còn yêu cầu nào đang chờ. Mọi thứ đã được xử lý.",
        TABLE_MEMBER: "Thành viên",
        TABLE_BOOK_TITLE: "Tựa sách yêu cầu",
        TABLE_MATCH: "Độ khớp",
        TABLE_ACTIONS: "Thao tác",
        BTN_REJECT: "Từ chối",
        BTN_APPROVE: "Duyệt",
    },
    SMART_CATALOGING: {
        TITLE: "Lên danh mục tự động",
        SUBTITLE: "Tải ảnh gáy sách hoặc mã ISBN — AI sẽ tự trích xuất thông tin.",
        DRAG_DROP: "Thả ảnh vào đây",
        OR_CLICK: "hoặc bấm để chọn tệp",
        MANUAL_ENTRY: "Nhập thủ công",
    },
    THONG_KE: {
        TITLE: "Thống kê",
        DESCRIPTION: "Trang thống kê sẽ chứa biểu đồ và số liệu tại đây.",
    },
};

export const ADMIN_LAYOUT = {
    TOPBAR: {
        HEADING: "Tổng quan",
        SUBHEADING: "Chào mừng trở lại, Admin. Đây là tình hình hôm nay.",
        SEARCH_PLACEHOLDER: "Tìm kho sách bằng ngữ nghĩa AI…",
        SEARCH_SHORTCUT: "⌘K",
    },
    ALERTS: {
        HEADING: "Cảnh báo hệ thống",
        SYNC_DELAY_TITLE: "Đồng bộ máy chủ bị trễ",
        SYNC_DELAY_DESC: "Kho Chi nhánh 8 chưa đồng bộ trong 2 giờ qua.",
        AI_UPDATE_TITLE: "Cập nhật mô hình AI",
        AI_UPDATE_DESC: "Tìm kiếm ngữ nghĩa được cải thiện cho thể loại lịch sử.",
    },
};

export const ADMIN_PAGES = {
    DASHBOARD: {
        BOOKS_TODAY: "Sách mượn hôm nay",
        BOOKS_TODAY_TREND: "+12% so với tuần trước",
        PENDING_APPROVAL: "Chờ phê duyệt",
        PENDING_APPROVAL_DESC: "Cần xem xét trong 24h",
        OVERDUE_BOOKS: "Sách quá hạn",
        OVERDUE_BOOKS_DESC: "Cần xử lý ngay",
    },
    MEMBERS: {
        TITLE: "Thành viên",
        DESC: "Trang quản lý thành viên thư viện sẽ hiển thị ở đây.",
    },
    BORROW_LOGS: {
        TITLE: "Lượt mượn",
        DESC: "Trang quản lý lượt mượn sách sẽ hiển thị thông tin ở đây.",
    },
    INVENTORY: {
        TITLE: "Kho sách",
        DESC: "Đây là trang kho sách. Bạn có thể thêm nội dung quản lý sách ở đây.",
    },
    SETTINGS: {
        TITLE: "Cài đặt",
        DESC: "Trang cài đặt của hệ thống quản lý thư viện.",
    },
};

export const ADMIN_SETTINGS = {
    TOPBAR_TITLE: "Admin Portal",
    PAGE_TITLE: "Chính sách nghiệp vụ",
    PAGE_DESCRIPTION: "Cấu hình tham số vận hành cốt lõi, ưu tiên khu vực và các tính năng toàn hệ thống cho nền tảng thư viện.",
    BORROWING: {
        TITLE: "Chính sách mượn sách",
        MAX_DAYS: "Số ngày mượn tối đa",
        FINE_PER_DAY: "Phạt mỗi ngày (VND)",
        MAX_BOOKS: "Số sách mượn đồng thời",
        DEPOSIT_PERCENTAGE: "Tỷ lệ đặt cọc",
        MAX_RENEWALS: "Số lần gia hạn tối đa",
        RENEWALS_HELP: "Số lần độc giả có thể gia hạn một lượt mượn trước khi trả sách.",
    },
    PAYMENTS: {
        TITLE: "Cổng thanh toán",
        ACTIVE: "Đang bật",
        INACTIVE: "Tạm tắt",
        VERIFIED: "Đã xác thực",
        NEEDS_CONNECTION: "Cần kết nối",
        MANAGE_CONNECTION: "Quản lý kết nối",
        CONNECT_GATEWAY: "Kết nối cổng",
        TOKEN_LABEL: "Mã kết nối",
        MOMO_TOKEN: "MOMO-LIVE-24",
        VNPAY_TOKEN: "CHƯA CẤP",
        MOMO_NAME: "MoMo Wallet",
        MOMO_DESC: "Tích hợp ví điện tử trực tiếp",
        MOMO_NOTE: "Sẵn sàng nhận tiền cọc và tiền phạt qua ví MoMo.",
        VNPAY_NAME: "VNPay",
        VNPAY_DESC: "Tích hợp chuyển khoản ngân hàng & QR",
        VNPAY_NOTE: "Cần nhập TmnCode, HashSecret và URL callback trước khi bật.",
    },
    FEATURES: {
        TITLE: "Tính năng hệ thống",
        AI_SEARCH_TITLE: "AI Semantic Search",
        AI_SEARCH_DESC: "Bật xử lý ngôn ngữ tự nhiên cho tìm kiếm danh mục công khai. Có thể tăng mức sử dụng API.",
        ONLINE_PAYMENTS_TITLE: "Thanh toán trực tuyến",
        ONLINE_PAYMENTS_DESC: "Cho phép độc giả thanh toán tiền phạt và tiền cọc qua các cổng đã tích hợp.",
        AUTO_BACKUP_TITLE: "Sao lưu tự động hằng ngày",
        AUTO_BACKUP_DESC: "Tự động tạo snapshot cơ sở dữ liệu lúc 02:00 theo giờ hệ thống.",
    },
    LOCALIZATION: {
        TITLE: "Bản địa hóa",
        LANGUAGE: "Ngôn ngữ",
        WORLD_CLOCK: "Đồng hồ thế giới",
        TIMEZONE: "Múi giờ hệ thống",
        VIETNAMESE: "Tiếng Việt (VN)",
        ENGLISH: "English (US)",
        BANGKOK_HANOI: "(UTC+07:00) Bangkok, Hà Nội, Jakarta",
        UTC: "UTC",
    },
    ACTION_BAR: {
        WARNING: "Các thay đổi chưa lưu sẽ bị mất nếu bạn rời trang này.",
        DISCARD: "Hủy bỏ",
        SAVE: "Lưu thay đổi",
        SUCCESS: "Cài đặt hệ thống đã được lưu thành công.",
        DISCARD_CONFIRM_TITLE: "Hủy thay đổi?",
        DISCARD_CONFIRM_MESSAGE: "Các thay đổi chưa lưu trên trang cài đặt sẽ bị mất. Bạn muốn tiếp tục chỉnh sửa hay hủy toàn bộ thay đổi?",
        KEEP_EDITING: "Tiếp tục chỉnh sửa",
        CONFIRM_DISCARD: "Hủy thay đổi",
    },
};

export const ADMIN_AUDIT_LOGS = {
    TOPBAR_TITLE: "Cổng quản trị",
    BREADCRUMB_LABEL: "Nhật ký hệ thống",
    PAGE_TITLE: "Nhật ký kiểm toán hệ thống",
    PAGE_DESCRIPTION:
        "Bản ghi theo trình tự thời gian về sự kiện hệ thống, hoạt động người dùng và các thao tác vận hành liên quan đến bảo mật trên toàn nền tảng.",
    QUICK_SEARCH_PLACEHOLDER: "Tìm nhanh ID hoặc người dùng...",
    TOPBAR_NOTIFICATIONS: "Thông báo",
    TOPBAR_SETTINGS: "Cài đặt",
    ADVANCED_FILTERS: "Bộ lọc nâng cao",
    EXPORT_RECORD: "Xuất bản ghi",
    EXPORT_FILENAME: "nhat-ky-kiem-toan-da-loc.txt",
    EXPORT_FORMAT_LABEL: "Định dạng file",
    EXPORT_FORMAT_TXT: "TXT",
    EXPORT_FORMAT_CSV: "CSV",
    EXPORT_FORMAT_JSON: "JSON",
    DETAIL_TITLE: "Xem chi tiết bản ghi",
    DETAIL_ACTION: "Xem chi tiết",
    FILTERS: {
        DATE_RANGE: "Khoảng thời gian",
        DATE_12_HOURS: "12 giờ",
        DATE_1_DAY: "1 ngày",
        DATE_3_DAYS: "3 ngày",
        DATE_7_DAYS: "7 ngày",
        DATE_ALL_TIME: "Từ trước tới nay",
        USER_ENTITY: "Người dùng / Đối tượng",
        ALL_USERS: "Tất cả",
        USERS: "Người dùng",
        ADMINS: "Quản trị viên",
        AUTOMATION: "Tự động hóa hệ thống",
        ACTION_TYPE: "Thao tác",
        ALL_ACTIONS: "Tất cả",
        AUTH_LOGIN: "Đăng nhập",
        RECORD_UPDATE: "Cập nhật bản ghi",
        PERMISSION_CHANGE: "Thay đổi quyền",
        KEYWORD: "Tìm kiếm",
        KEYWORD_PLACEHOLDER: "VD: '192.168.1.1' hoặc 'xoa_bo_du_lieu'",
    },
    TABLE: {
        TIMESTAMP: "Thời điểm",
        USER_ENTITY: "Người dùng / Đối tượng",
        ACTION: "Thao tác",
        TARGET_OBJECT: "Đối tượng tác động",
        IP_ADDRESS: "Địa chỉ IP",
        RESULT: "Kết quả",
        PAGINATION_SUMMARY: "Hiển thị {start}-{end} trong {total} bản ghi",
        EMPTY_PAGE: "Trang này chưa có bản ghi.",
        PAGE_LABEL: "Trang",
        PREVIOUS_PAGE: "Trang trước",
        NEXT_PAGE: "Trang sau",
    },
    RESULT: {
        SUCCESS: "Thành công",
        FAILED: "Thất bại",
        BLOCKED: "Đã chặn",
    },
    DETAIL: {
        TIMESTAMP: "Thời điểm ghi nhận",
        ACTOR: "Người thực hiện",
        ACTION: "Thao tác",
        TARGET: "Đối tượng tác động",
        IP_ADDRESS: "Địa chỉ IP",
        RESULT: "Kết quả",
        DESCRIPTION: "Mô tả",
    },
};
