export const AUTH = {
    LOGIN: {
        HEADING: "Chào mừng quay trở lại",
        SUBHEADING: "Đăng nhập để truy cập Thư viện.",
        EMAIL_LABEL: "Email",
        EMAIL_PLACEHOLDER: "Email của bạn",
        PASSWORD_LABEL: "Mật khẩu",
        PASSWORD_PLACEHOLDER: "Mật khẩu của bạn",
        HIDE_PASSWORD_ARIA: "Ẩn mật khẩu",
        SHOW_PASSWORD_ARIA: "Hiện mật khẩu",
        FORGOT_PASSWORD: "Quên mật khẩu?",
        SUBMIT_BTN: "Đăng nhập",
        OR_CONTINUE_WITH: "Đăng nhập với",
        NO_ACCOUNT: "Không có tài khoản?",
        SIGN_UP_LINK: "Đăng ký",
        GOOGLE_BTN: "Google",
        APPLE_BTN: "Apple",
        VALIDATION: {
            EMAIL_REQUIRED: "Email không được để trống.",
            EMAIL_INVALID: "Email không hợp lệ.",
            PASSWORD_REQUIRED: "Mật khẩu không được để trống.",
            PASSWORD_MIN_LENGTH: "Mật khẩu phải có ít nhất 6 ký tự.",
        },
        ERROR_MSG: "Đăng nhập thất bại. Vui lòng thử lại.",
        REGISTER_SUCCESS: "Đăng ký thành công! Vui lòng đăng nhập.",
    },
    REGISTER: {
        HEADING: "Tạo tài khoản",
        FULL_NAME_LABEL: "Họ và tên",
        FULL_NAME_PLACEHOLDER: "Nguyễn Văn A",
        PHONE_LABEL: "Số điện thoại",
        PHONE_PLACEHOLDER: "0901234567",
        EMAIL_LABEL: "Email",
        EMAIL_PLACEHOLDER: "Email của bạn",
        PASSWORD_LABEL: "Mật khẩu",
        PASSWORD_PLACEHOLDER: "Nhập mật khẩu",
        CONFIRM_PASSWORD_LABEL: "Xác nhận mật khẩu",
        CONFIRM_PASSWORD_PLACEHOLDER: "Xác nhận mật khẩu",
        SUBMIT_BTN: "Đăng ký →",
        LOADING_BTN: "Đang xử lý...",
        ERROR_MSG: "Đăng ký thất bại. Vui lòng thử lại.",
        ALREADY_HAVE_ACCOUNT: "Đã có tài khoản?",
        LOGIN_LINK: "Đăng nhập ngay",
        ERROR_ICON: "⚠️",
    },
    BANNER: {
        IMG_ALT: "Không gian thư viện Lumina",
        LOGO_TEXT: "Lumina Library",
        HERO_HEADING: "Tìm kiếm tri thức từ điều nhỏ nhất.",
        HERO_SUBHEADING: "Cánh cửa dẫn bạn đến với kho tàng tri thức của nhân loại.",
        COPYRIGHT: "© 2026 Lumina Library",
    },
    ADMIN_GUARD: {
        ACCESS_DENIED: "Truy cập bị từ chối",
        NO_PERMISSION: "Tài khoản của bạn không có quyền truy cập vào trang Quản trị. Vui lòng liên hệ quản trị viên nếu bạn nghĩ đây là sự nhầm lẫn.",
        BACK_TO_HOME: "Quay về trang chủ",
    },
};
