export const BORROW = {
    TITLE: "Yêu cầu mượn sách",
    SUBTITLE: "Xác nhận chi tiết mượn sách và chọn lịch lấy sách.",
    BACK_TO_CATALOG: "Trở lại danh mục",
    FORM: {
        SELECTED_TITLE: "Sách đã chọn",
        PICKUP_DATE: "Ngày lấy sách",
        RETURN_DATE: "Ngày trả sách",
        PAYMENT_METHOD: "Phương thức cọc",
        CASH: "Tiền mặt khi nhận",
        MOMO: "Ví MoMo",
        VNPAY: "Ví VNPay",
    },
    POLICY: {
        TITLE: "Chính sách mượn sách:",
        CONTENT:
            "Mỗi độc giả được mượn tối đa 3 cuốn sách giấy. Vui lòng đảm bảo trả sách trong thời hạn 14 ngày để tránh phí phạt trễ hạn hoặc bị tạm khóa tài khoản.",
    },
    SUMMARY: {
        TITLE: "Tóm tắt mượn sách",
        BORROWER: "Người mượn",
        LOAN_PERIOD: "Thời hạn mượn",
        LOAN_PERIOD_VALUE: "14 Ngày",
        LATE_FEE_RATE: "Phí phạt trễ hạn",
        LATE_FEE_RATE_VALUE: "10.000đ / ngày",
        REFUNDABLE_DEPOSIT: "Tiền cọc (Hoàn lại)",
        CURRENCY: "đ",
        CONFIRM_BUTTON: "Xác nhận yêu cầu mượn",
        PROCESSING: "Đang xử lý...",
        SUCCESS: "Đã gửi yêu cầu!",
        SECURED_BY: "Bảo mật bởi Lumina Intelligence",
    },
    SUPPORT: {
        TITLE: "Cần hỗ trợ?",
        DESCRIPTION: "Thủ thư AI của chúng tôi làm việc 24/7 để giải đáp thắc mắc về địa điểm lấy sách và gia hạn.",
        BUTTON: "Mở Chat Thư viện",
    },
    SUCCESS_PAGE: {
        TITLE: "Gửi yêu cầu mượn thành công!",
        REQUEST_ID: "Mã yêu cầu",
        PENDING_APPROVAL: "Yêu cầu mượn sách của bạn đang chờ đội ngũ quản lý phê duyệt. Một email xác nhận đã được gửi đến hộp thư của bạn.",
        VIEW_LOANS: "Xem sách đang mượn",
        CONTINUE_BROWSING: "Tiếp tục tìm sách",
        HOW_LONG: "Quá trình phê duyệt mất bao lâu?",
    },
};
