import { ADMIN, ADMIN_AUDIT_LOGS, ADMIN_BORROW_MANAGEMENT, ADMIN_LAYOUT, ADMIN_PAGES, ADMIN_SETTINGS, ADMIN_USER_MANAGEMENT } from "./admin";
import { AUTH } from "./auth";
import { BORROW } from "./borrow";
import { COMMON, MAINTENANCE } from "./common";
import { NOTIFICATIONS } from "./notifications";
import { ABOUT, BOOK_DETAIL, BOOK_LIST, CONTACT, HOME, MY_BOOKS_PAGE, PUBLIC_LAYOUT, RENEW_PAGE } from "./public";
import { ROLES } from "./roles";
import { PROFILE, SETTINGS_HEADER, SETTINGS_NOTIFICATIONS, SETTINGS_SECURITY, SETTINGS_SIDEBAR } from "./settings";

export const UI_TEXT = {
    COMMON,
    AUTH,
    NOTIFICATIONS,
    ADMIN,
    PUBLIC_LAYOUT,
    BOOK_LIST,
    BOOK_DETAIL,
    HOME,
    ABOUT,
    CONTACT,
    MY_BOOKS_PAGE,
    RENEW_PAGE,
    BORROW,
    ADMIN_LAYOUT,
    ADMIN_PAGES,
    ADMIN_SETTINGS,
    ADMIN_AUDIT_LOGS,
    ADMIN_USER_MANAGEMENT,
    ADMIN_BORROW_MANAGEMENT,
    MAINTENANCE,
    PROFILE,
    SETTINGS_HEADER,
    SETTINGS_SIDEBAR,
    SETTINGS_NOTIFICATIONS,
    SETTINGS_SECURITY,
    ROLES,
};
