import {
    ADMIN,
    ADMIN_ANALYTICS,
    ADMIN_AUDIT_LOGS,
    ADMIN_BORROW_MANAGEMENT,
    ADMIN_LAYOUT,
    ADMIN_PAGES,
    ADMIN_REVIEWS,
    ADMIN_SETTINGS,
    ADMIN_USER_MANAGEMENT,
    ROLES,
} from "./admin";
import { AUTH } from "./auth";
import { COMMON, MAINTENANCE } from "./common";
import { ABOUT, BOOK_DETAIL, BOOK_LIST, BOOK_VISIT, BORROW, CONTACT, FAVORITE, HOME, MY_BOOKS_PAGE, NOTIFICATIONS, PUBLIC_LAYOUT, RENEW_PAGE } from "./public";
import { PROFILE, SETTINGS_HEADER, SETTINGS_NOTIFICATIONS, SETTINGS_SECURITY, SETTINGS_SIDEBAR } from "./settings";

export const UI_TEXT = {
    COMMON,
    AUTH,
    NOTIFICATIONS,
    ADMIN,
    PUBLIC_LAYOUT,
    BOOK_LIST,
    BOOK_DETAIL,
    BOOK_VISIT,
    HOME,
    ABOUT,
    CONTACT,
    FAVORITE,
    MY_BOOKS_PAGE,
    RENEW_PAGE,
    BORROW,
    ADMIN_LAYOUT,
    ADMIN_PAGES,
    ADMIN_SETTINGS,
    ADMIN_AUDIT_LOGS,
    ADMIN_USER_MANAGEMENT,
    ADMIN_BORROW_MANAGEMENT,
    ADMIN_ANALYTICS,
    ADMIN_REVIEWS,
    MAINTENANCE,
    PROFILE,
    SETTINGS_HEADER,
    SETTINGS_SIDEBAR,
    SETTINGS_NOTIFICATIONS,
    SETTINGS_SECURITY,
    ROLES,
};
