import { ADMIN, ADMIN_AUDIT_LOGS, ADMIN_LAYOUT, ADMIN_PAGES, ADMIN_SETTINGS } from "./admin";
import { AUTH } from "./auth";
import { COMMON, MAINTENANCE } from "./common";
import { NOTIFICATIONS } from "./notifications";
import { ABOUT, BOOK_DETAIL, BOOK_LIST, CONTACT, HOME, PUBLIC_LAYOUT } from "./public";
import { PROFILE, SETTINGS_HEADER, SETTINGS_NOTIFICATIONS, SETTINGS_SECURITY, SETTINGS_SIDEBAR } from "./settings";

export const UI_TEXT = {
    COMMON,
    AUTH,
    NOTIFICATIONS,
    ADMIN,
    PUBLIC_LAYOUT,
    BOOK_LIST,
    BOOK_DETAIL,
    HOME,
    ABOUT,
    CONTACT,
    ADMIN_LAYOUT,
    ADMIN_PAGES,
    ADMIN_SETTINGS,
    ADMIN_AUDIT_LOGS,
    MAINTENANCE,
    PROFILE,
    SETTINGS_HEADER,
    SETTINGS_SIDEBAR,
    SETTINGS_NOTIFICATIONS,
    SETTINGS_SECURITY,
};
