export const PUBLIC_LAYOUT = {
    MY_ACCOUNT: "Tài khoản của tôi",
    MY_BOOKS: "Sách của tôi",
    LOGOUT: "Đăng xuất",
    LOGIN: "Đăng nhập",
    ARIA: {
        TOGGLE_THEME: "Đổi chế độ màu",
        NOTIFICATIONS: "Thông báo",
        PROFILE: "Hồ sơ cá nhân",
        USER_MENU: "Menu người dùng",
    },
    NAV_LINKS: {
        HOME: "Trang chủ",
        BOOK: "Danh sách sách",
        ABOUT: "Giới thiệu",
        CONTACT: "Liên hệ",
    },
    FOOTER_LINKS: {
        TERMS: "Terms of Service",
        PRIVACY: "Privacy Policy",
        CONTACT: "Contact Support",
        API_DOCS: "API Docs",
        COPYRIGHT: "© 2026 Lumina Library AI. Powered by Illuminated Intelligence.",
    },
};

export const BOOK_LIST = {
    BREADCRUMB_HOME: "Trang chủ",
    BREADCRUMB_LIST: "Danh sách sách",
    HERO_HEADING: "Khám phá Tri thức",
    HERO_SUBHEADING: "Tìm kiếm, khám phá và đắm chìm trong thế giới sách đa dạng của chúng tôi. Hàng ngàn đầu sách đang chờ bạn.",
    SEARCH_PLACEHOLDER: "Tìm kiếm theo tên sách, tác giả...",
    SIDEBAR_CATEGORY: "Danh mục",
    SIDEBAR_FILTER: "Lọc theo",
    SORT_LABEL: "Sắp xếp",
    SORT_OPTIONS: {
        NEWEST: "Mới nhất",
        TOP_RATED: "Đánh giá cao nhất",
        POPULAR: "Phổ biến nhất",
    },
    RESULTS_COUNT_PRE: "Hiển thị",
    RESULTS_COUNT_POST: "kết quả",
    RESULTS_FOR: "cho",
    IMAGE_ALT: "Bìa sách:",
    NO_RESULTS_HEADING: "Không tìm thấy sách nào",
    NO_RESULTS_DESC: "Hãy thử thay đổi tiêu chí tìm kiếm hoặc danh mục để xem thêm kết quả.",
    CLEAR_FILTER_BTN: "Xóa bộ lọc",
    CATEGORIES: {
        ALL: "Tất cả",
        SCIENCE: "Khoa học & Công nghệ",
        FICTION: "Tiểu thuyết",
        HISTORY: "Lịch sử",
        DESIGN: "Thiết kế & Nghệ thuật",
        BUSINESS: "Kinh doanh",
    },
};

export const HOME = {
    HERO_HEADING: "TÌM KIẾM TRI THỨC CÙNG AI",
    HERO_SUBHEADING: "Tìm kiếm những cuốn sách yêu thích của bạn dễ dàng hơn với công nghệ AI.",
    SEARCH_PLACEHOLDER: "Tìm kiếm sách...",
    SEARCH_BTN: "Tìm kiếm với AI",
    CURATED_HEADING: "Dành cho bạn",
    CURATED_SUBHEADING: "Đề xuất dựa trên sở thích đọc sách của bạn.",
    MATCH_SUFFIX: "% phù hợp.",
    EXPLORE_COLLECTION: "Khám phá bộ sưu tập",
    TRENDING_HEADING: "Đang thịnh hành",
    TRENDING_SUBHEADING: "Xu hướng hiện tại.",
    VIEW_ALL: "Xem tất cả",
    CATEGORIES: {
        SCIENCE: "Khoa học",
        NOVEL: "Tiểu thuyết",
        HISTORY: "Lịch sử",
        DESIGN: "Thiết kế",
    },
    BADGES: {
        TRENDING_1: "#1 Thịnh hành",
    },
    CURATED_SECTION: {
        DEEP_DIVE: "Deep Dive",
        PHILOSOPHY_AI: "The Philosophy of Artificial Intelligence",
        PHILOSOPHY_AI_DESC: "A comprehensive collection exploring the ethical and societal implications of thinking machines.",
        HARD_SCIFI: "Hard Sci-Fi Essentials",
        HARD_SCIFI_DESC: "Highly technical speculative fiction based on your recent searches.",
        BOOKS_12: "12 Books",
        WORLD_BUILDING: "World Building Masterclass",
        WORLD_BUILDING_DESC: "Because you read 'Dune' and 'Foundation'.",
    },
};

export const ABOUT = {
    PAGE_TITLE: "Giới thiệu | Lumina Library",
    PAGE_DESC: "Khám phá câu chuyện của Lumina Library — hệ thống thư viện thông minh kết hợp truyền thống.",
    HERO_HEADING: "Khai sáng tri thức bằng AI",
    HERO_DESC_1:
        "Lumina Library kết nối di sản sâu sắc của kho tàng truyền thống với tốc độ liền mạch của trí tuệ nhân tạo hiện đại. Chúng tôi đang tái định nghĩa sự khám phá.",
    EXPLORE_VISION: "Khám phá tầm nhìn",
    STORY_HEADING: "Câu chuyện của chúng tôi",
    STORY_DESC_1:
        "Khởi nguồn từ mong muốn biến đại dương tri thức bao la của nhân loại trở nên dễ dàng tiếp cận, Lumina Library bắt đầu như một sáng kiến nghiên cứu về xử lý ngữ nghĩa tiên tiến.",
    STORY_DESC_2:
        "Ngày nay, chúng tôi cung cấp sự tổng hòa tinh tế giữa chủ nghĩa hiện đại doanh nghiệp và công nghệ AI cao cấp, đảm bảo rằng dù bạn đang tìm kiếm luận văn học thuật hay tiểu thuyết, mọi thứ đều hiển hiện ngay trước mắt.",
    ARIA_HERO: "Không gian thư viện hiện đại với kiến trúc hùng vĩ",
    ARIA_STORY: "Giao diện hệ thống quản lý thư viện thông minh",
    CORE_VALUES: {
        HEADING: "Giá trị cốt lõi",
        SUBHEADING: "Những nguyên tắc dẫn dắt trí tuệ của chúng tôi.",
        V1_TITLE: "Đổi mới",
        V1_DESC: "Tiên phong trong giao diện mượt mà và tìm kiếm ngữ nghĩa để phát triển cách chúng ta tương tác với dữ liệu.",
        V2_TITLE: "Tiếp cận",
        V2_DESC: "Thiết kế hệ thống toàn diện giúp mọi người, ở mọi nơi, khám phá và học hỏi một cách dễ dàng.",
        V3_TITLE: "Chính trực",
        V3_DESC: "Duy trì sức nặng thẩm quyền và sự thật nghiêm ngặt của thư viện truyền thống trong mọi tương tác AI.",
    },
};

export const CONTACT = {
    PAGE_TITLE: "Liên hệ | Lumina Library",
    PAGE_DESC: "Liên hệ với đội ngũ Lumina Library — giải đáp thắc mắc về thư viện, sách và các thông tin khác",
    HEADING: "Liên hệ với chúng tôi",
    SUBHEADING: "Bạn có câu hỏi về bộ sưu tập, khả năng tìm kiếm AI, hoặc truy cập tổ chức? Đội ngũ tận tâm của chúng tôi luôn sẵn sàng hỗ trợ bạn.",
    FORM_HEADING: "Gửi tin nhắn",
    NAME_LABEL: "Họ và tên",
    NAME_PLACEHOLDER: "Nguyễn Văn A",
    EMAIL_LABEL: "Địa chỉ Email",
    SUBJECT_LABEL: "Chủ đề",
    SUBJECT_OPTIONS: {
        DEFAULT: "Chọn loại yêu cầu...",
        ACCESS: "Truy cập Tổ chức",
        TECH_SUPPORT: "Hỗ trợ Kỹ thuật (Tìm kiếm AI)",
        COLLECTION: "Đề xuất Bộ sưu tập",
        OTHER: "Yêu cầu khác",
    },
    MESSAGE_LABEL: "Nội dung",
    MESSAGE_PLACEHOLDER: "Chúng tôi có thể hỗ trợ bạn điều gì?",
    SUBMIT_BTN: "Gửi yêu cầu",
    INFO_HEADING: "Thông tin liên hệ",
    ADDRESS_LABEL: "Địa chỉ",
    ADDRESS_LINE_1: "Lumina Campus",
    ADDRESS_LINE_2: "404 Knowledge Parkway",
    ADDRESS_LINE_3: "Innovation District, CA 90210",
    SUPPORT_LABEL: "Hỗ trợ chung",
    PHONE: "+1 (800) 555-0199",
    INFO_EMAIL_LABEL: "Email",
    EMAIL: "research@luminalibrary.edu",
    DIRECTIONS_BTN: "Chỉ đường",
    MAP_ALT: "Bản đồ vị trí Lumina Campus",
    FAQ_HEADING: "Câu hỏi thường gặp",
    FAQ_SUBHEADING: "Giải đáp nhanh các thắc mắc phổ biến.",
    FAQS: [
        {
            QUESTION: "Làm thế nào để mượn sách từ thư viện thông qua website?",
            ANSWER: "Bạn chỉ cần vào danh mục, tìm kiếm sách, chọn sách muốn mượn và chờ nhân viên thư viện xử lý nếu mượn sách trực tuyến. Sau đó, bạn có thể nhận sách tại quầy hoặc yêu cầu giao sách đến tận nơi.",
        },
        {
            QUESTION: "Tôi có thể mượn sách dễ dàng không?",
            ANSWER: "Có, Lumina Library cho phép mượn sách dễ dàng thông qua website hoặc mượn trực tiếp từ thư viện",
        },
        {
            QUESTION: "Giờ hoạt động của thư viện là bao nhiêu?",
            ANSWER: "Các phòng đọc tại thư viện mở cửa từ Thứ Hai đến Thứ Sáu, 8:00 sáng đến 9:00 tối. Truy cập cuối tuần được giới hạn cho các nghiên cứu sinh cao cấp theo lịch hẹn. Danh mục kỹ thuật số hoạt động 24/7.",
        },
    ],
};

export const BOOK_DETAIL = {
    RELATED_BOOKS_HEADING: "Related Titles",
    VIEW_ALL: "View all",
    REVIEWS: "Reviews",
    BY: "By",
    TAGS_CATEGORIES: "Tags & Categories",
    MATCH_SCORE_SUFFIX: "% Match",
    BORROW_NOW: "Borrow Now",
    ADD_WISHLIST: "Add to Wishlist",
    AI_CHATBOT: {
        TITLE: "Lumina AI",
        SUBTITLE: "Book Summary & Reading Path",
    },
};

export const MY_BOOKS_PAGE = {
    TITLE: "Lịch sử mượn sách",
    BREADCRUMB_ACCOUNT: "Tài khoản",
    STATUS_OVERDUE: "Quá hạn (3 ngày)",
    RENEW_NOW: "Gia hạn ngay",
    FILTER: {
        STATUS_LABEL: "Trạng thái",
        STATUS_ALL: "Tất cả trạng thái",
        STATUS_BORROWING: "Đang mượn",
        STATUS_RETURNED: "Đã trả",
        STATUS_OVERDUE: "Quá hạn",
        STATUS_PENDING: "Chờ phê duyệt",
        STATUS_CANCELLED: "Đã hủy",
        DATE_RANGE_LABEL: "Khoảng thời gian",
        DATE_TO: "đến",
        APPLY_BUTTON: "Áp dụng bộ lọc",
    },
    CARD: {
        AUTHOR_PREFIX: "Tác giả:",
        BORROW_DATE: "Ngày mượn",
        DUE_DATE: "Hạn trả dự kiến",
        ACTUAL_RETURN_DATE: "Ngày trả thực tế",
        DEPOSIT: "Tiền đặt cọc",
        LATE_FEE_LABEL: "Tiền phạt phát sinh",
        DEPOSIT_RETURN: "Hoàn trả cọc",
        VIEW_DETAIL: "Xem chi tiết",
        VIEW_RECEIPT: "Xem biên lai",
        STATUS_BORROWING: "Đang mượn",
        STATUS_RETURNED: "Đã trả",
    },
    EMPTY_STATE: {
        HEADING: "Bạn chưa có lịch sử mượn sách",
        DESC: "Hãy bắt đầu hành trình khám phá kho tri thức khổng lồ của Lumina Library ngay hôm nay.",
        BROWSE_BUTTON: "Duyệt kho sách ngay",
    },
};
