server:
  port: ${PORT:8081}

spring:
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:.env.backend[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc.time_zone: Asia/Ho_Chi_Minh
        default_batch_fetch_size: 100
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 900000
