export const SETTINGS_SECURITY = {
    PAGE: {
        HEADING: "Cài đặt bảo mật",
        SUBHEADING: "Quản lý thông tin đăng nhập, bật xác thực hai lớp và theo dõi các phiên đang hoạt động trong hệ thống Lumina.",
        CHANGE_PASSWORD: "Đổi mật khẩu",
        CURRENT_PASSWORD_LABEL: "Mật khẩu hiện tại",
        CURRENT_PASSWORD_PLACEHOLDER: "Nhập mật khẩu hiện tại",
        NEW_PASSWORD_LABEL: "Mật khẩu mới",
        NEW_PASSWORD_PLACEHOLDER: "Tối thiểu 8 ký tự",
        CONFIRM_NEW_LABEL: "Xác nhận mật khẩu mới",
        CONFIRM_NEW_PLACEHOLDER: "Nhập lại mật khẩu mới",
        UPDATE_PASSWORD_BTN: "Cập nhật mật khẩu",
        PASSWORD_ELIGIBLE: "Đủ điều kiện",
        PASSWORD_INELIGIBLE: "Chưa đủ điều kiện",
        PASSWORD_MATCH: "Trùng khớp",
        PASSWORD_MISMATCH: "Chưa trùng khớp",
        TWO_FACTOR_TITLE: "Xác thực hai lớp",
        TWO_FACTOR_DESC: "Thêm một lớp bảo vệ cho tài khoản của bạn. Chúng tôi khuyến nghị bật tính năng này để bảo vệ lịch sử đọc và dữ liệu cá nhân.",
        TWO_FACTOR_ENABLED: "Đang bật",
        TWO_FACTOR_DISABLED: "Đang tắt",
        LOGIN_ACTIVITY: "Hoạt động đăng nhập",
        LOG_OUT_ALL_BTN: "Đăng xuất tất cả",
        EMPTY_SESSIONS: "Không có phiên đăng nhập nào.",
        ACTIVE_NOW: "Đang hoạt động",
        SUCCESS_MESSAGES: {
            PASSWORD_UPDATED: "Mật khẩu đã được cập nhật thành công.",
            TWO_FACTOR_ENABLED: "Xác thực hai lớp đã được bật.",
            TWO_FACTOR_DISABLED: "Xác thực hai lớp đã được tắt.",
            LOGGED_OUT_ALL: "Tất cả phiên đăng nhập khác đã được đăng xuất.",
        },
        SESSIONS: {
            MACBOOK_TITLE: "MacBook Pro - Safari",
            MACBOOK_SUBTITLE: "San Francisco, CA, Hoa Kỳ - 192.168.1.1",
            IPHONE_TITLE: "iPhone 13 - Ứng dụng Lumina",
            IPHONE_SUBTITLE: "San Jose, CA, Hoa Kỳ - Hôm qua, 16:20",
            WINDOWS_TITLE: "Windows PC - Chrome",
            WINDOWS_SUBTITLE: "Seattle, WA, Hoa Kỳ - 12/10, 10:05",
        },
    },
};
