export const API_SUCCESS = {
    FAVORITE_ADD_SUCCESS: "Đã thêm vào danh sách yêu thích",
    FAVORITE_REMOVE_SUCCESS: "Đã xóa khỏi danh sách yêu thích",
    HOLD_CANCEL_SUCCESS: "Đã huỷ đặt giữ chỗ thành công!",
};

export const API_ERRORS = {
    FAVORITE_UPDATE_FAILED: "Cập nhật danh sách yêu thích thất bại",
    BOOK_LOAD_FAILED: "Lỗi tải thông vị sách",
    BOOK_DETAIL_FAILED: "Lỗi tải chi tiết sách",
    BOOK_TRENDING_FAILED: "Lỗi tải sách thịnh hành",
    BOOK_RELATED_FAILED: "Lỗi tải sách liên quan",
    CATEGORY_LOAD_FAILED: "Lỗi tải danh mục",
    USER_BORROW_HISTORY_FAILED: "Lỗi tải lịch sử mượn sách",
    USER_BORROW_DETAIL_FAILED: "Lỗi tải chi tiết mượn sách",
    GOOGLE_LOGIN_FAILED: "Đăng nhập Google thất bại",
    HOLD_CANCEL_FAILED: "Huỷ đặt giữ chỗ thất bại",
    FAVORITE_ADD_FAILED: "Thêm vào danh sách yêu thích thất bại",
    LOGIN_FAILED: "Đăng nhập thất bại",
    FAVORITE_LOAD_FAILED: "Lỗi tải danh sách yêu thích",
    RECOMMENDATION_LOAD_FAILED: "Lỗi tải gợi ý sách",
    SEARCH_FAILED: "Tra cứu thất bại. Vui lòng kiểm tra lại thông tin.",
    GENERIC_ERROR: "Đã có lỗi xảy ra",
    FETCH_ERROR: "Không thể tải dữ liệu",
    FETCH_DETAIL_ERROR: "Không thể tải chi tiết đơn mượn",
    NOT_FOUND_LOAN: "Không tìm thấy thông tin đơn mượn",
    NOT_FOUND_BOOK: "Không tìm thấy sách",
    RENEW_FAILED: "Gia hạn thất bại",
    RENEW_REQUEST_ERROR: "Đã xảy ra lỗi khi gửi yêu cầu gia hạn",
    GENERIC_FETCH_ERROR: "Lỗi khi tải dữ liệu",
    CREATE_BORROW_FAILED: "Tạo phiếu mượn thất bại",
    FETCH_AUTHORS_ERROR: "Lỗi khi tải danh sách tác giả",
    DELETE_AUTHOR_ERROR: "Lỗi khi xoá tác giả",
    SAVE_AUTHOR_ERROR: "Lỗi khi lưu tác giả",
    FETCH_CATEGORIES_ERROR: "Lỗi khi tải danh sách thể loại",
    DELETE_CATEGORY_ERROR: "Lỗi khi xoá thể loại",
    SAVE_CATEGORY_ERROR: "Lỗi khi lưu thể loại",
    FETCH_BOOK_ERROR: "Lỗi khi tải thông tin sách",
    SAVE_BOOK_ERROR: "Lỗi khi lưu sách",
    FETCH_BORROW_ERROR: "Lỗi khi tải dữ liệu lượt mượn",
    FETCH_BORROW_DETAIL_ERROR: "Đã có lỗi xảy ra khi tải chi tiết",
    MISSING_FIELDS: "Vui lòng điền các thông tin bắt buộc (SĐT, Mã vạch, Ngày hẹn trả)",
    MISSING_BARCODE: "Vui lòng nhập ít nhất một mã vạch hợp lệ",
    NAME_REQUIRED: "Tên không được để trống",
    EMAIL_REQUIRED: "Email không được để trống",
    PASSWORD_MIN_LENGTH: "Mật khẩu phải có ít nhất 8 ký tự",
    SAVE_USER_FAILED: "Lưu thông tin thất bại",
    UPDATE_STATUS_FAILED: "Cập nhật trạng thái thất bại. Vui lòng thử lại!",
    RENEW_APPROVE_FAILED: "Xử lý duyệt gia hạn thất bại. Vui lòng thử lại!",
    SAVE_POLICY_FAILED: "Lưu chính sách thất bại",
};
