export const BOOK_VISIT = {
    SIDEBAR: {
        HEADING: "Đọc tại thư viện",
        MENU: {
            BOOK_VISIT: "Đặt lịch đọc sách",
        },
    },
    HERO: {
        BADGE: "Smart Access",
        TITLE: "Đặt lịch đọc sách",
        DESCRIPTION: "Chọn thời gian đến Lumina Library để đọc sách trong không gian yên tĩnh, có sẵn khu vực học tập và hỗ trợ tại quầy.",
    },
    FORM: {
        GUEST_SECTION: "Thông tin người đọc",
        LOGISTICS_SECTION: "Lịch đến thư viện",
        FULL_NAME_LABEL: "Họ và tên",
        FULL_NAME_PLACEHOLDER: "Nhập họ và tên",
        EMAIL_LABEL: "Địa chỉ email",
        EMAIL_PLACEHOLDER: "xxx@gmail.com",
        PHONE_LABEL: "Số điện thoại",
        PHONE_PLACEHOLDER: "Nhập số điện thoại",
        DATE_LABEL: "Ngày đến",
        TIME_LABEL: "Giờ đến",
        TIME_PLACEHOLDER: "Chọn giờ đến",
        TIME_DISABLED_PLACEHOLDER: "Chọn ngày đến trước",
        PURPOSE_LABEL: "Mục đích chính",
        PURPOSE_PLACEHOLDER: "Chọn mục đích...",
        PURPOSE_OPTIONS: {
            READ: "Đọc sách tại chỗ",
            STUDY: "Tự học trong phòng đọc",
            RESEARCH: "Nghiên cứu tài liệu",
            CONSULT: "Nhờ thủ thư tư vấn",
        },
        NOTE: "Không cần tạo tài khoản mới. Xác nhận đặt lịch sẽ được gửi qua email để vào thư viện nhanh hơn.",
        SUBMIT: "Xác nhận lịch đến",
        TOAST_SENDING: "Đang gửi xác nhận lịch đến...",
    },
    SUCCESS: {
        PAGE_TITLE: "Đặt lịch đọc sách thành công",
        TITLE: "Đặt lịch thành công!",
        DESCRIPTION: "Lịch đến Lumina Library của bạn đã được ghi nhận. Chúng tôi sẽ chuẩn bị không gian đọc và hỗ trợ khi bạn đến.",
        REFERENCE_LABEL: "Mã xác nhận",
        DATE_LABEL: "Ngày",
        TIME_LABEL: "Giờ",
        PURPOSE_LABEL: "Mục đích",
        INBOX_TITLE: "Kiểm tra email của bạn",
        INBOX_DESC: "Thông tin xác nhận đã được gửi đến email đã đăng ký. Vui lòng chuẩn bị mã xác nhận này khi đến quầy lễ tân.",
        ADD_TO_CALENDAR: "Thêm vào lịch",
        RETURN_HOME: "Về trang chủ",
        FALLBACK_REFERENCE: "LM-APP-0000",
        FALLBACK_DATE: "Đang cập nhật",
        FALLBACK_TIME: "Đang cập nhật",
        FALLBACK_PURPOSE: "Đọc sách tại thư viện",
        CALENDAR_TITLE: "Lịch đọc sách tại Lumina Library",
        CALENDAR_DETAILS_PREFIX: "Mã xác nhận",
        PURPOSE_OPTIONS: {
            READ: "Đọc sách tại chỗ",
            STUDY: "Tự học trong phòng đọc",
            RESEARCH: "Nghiên cứu tài liệu",
            CONSULT: "Nhờ thủ thư tư vấn",
        },
    },
    INFO: {
        IMAGE_ALT: "Không gian phòng đọc của Lumina Library",
        IMAGE_TITLE: "Phòng đọc Lumina",
        IMAGE_DESC: "Khu vực yên tĩnh, ánh sáng tự nhiên và bàn đọc rộng rãi.",
        BOOK_LABEL: "Sách đã chọn",
        BOOK_FALLBACK: "Sách trong thư viện Lumina",
        BOOK_LOADING: "Đang tải thông tin sách...",
        BOOK_ERROR: "Không thể tải tên sách, bạn vẫn có thể đặt lịch đến thư viện.",
        LOCATION_TITLE: "Địa điểm & giờ mở cửa",
        BRANCH: "Lumina Campus",
        ADDRESS_LINE_1: "404 Knowledge Parkway",
        ADDRESS_LINE_2: "Innovation District, CA 90210",
        WEEKDAY_LABEL: "Thứ 2 - Thứ 6",
        WEEKDAY_TIME: "08:00 - 20:00",
        WEEKEND_LABEL: "Thứ 7 - Chủ nhật",
        WEEKEND_TIME: "09:30 - 17:30",
        POLICY_TITLE: "Lưu ý khi đến",
        POLICY_ITEMS: [
            "Mang theo email xác nhận khi vào thư viện.",
            "Giữ im lặng tại khu vực phòng đọc.",
            "Đến đúng khung giờ đã đăng ký để được hỗ trợ nhanh.",
        ],
        BENEFITS_TITLE: "Tiện ích đi kèm:",
        BENEFITS: {
            WIFI: "Wifi miễn phí tốc độ cao",
            WORKSPACE: "Bàn học/làm việc riêng tư",
            AIR_CONDITIONER: "Điều hòa, ánh sáng tiêu chuẩn",
            SUPPORT: "Hỗ trợ tài liệu từ thủ thư",
        },
    },
    ACTIONS: {
        BACK_TO_BOOK: "Quay lại chi tiết sách",
        MEMBER_LOGIN: "Đăng nhập thành viên",
    },
};
