export const BOOK_LIST = {
    BREADCRUMB_HOME: "Trang chủ",
    BREADCRUMB_LIST: "Danh sách sách",
    HERO_HEADING: "Khám phá Tri thức",
    HERO_SUBHEADING: "Tìm kiếm, khám phá và đắm chìm trong thế giới sách đa dạng của chúng tôi. Hàng ngàn đầu sách đang chờ bạn.",
    SEARCH_PLACEHOLDER: "Tìm kiếm theo tên sách, tác giả...",
    SIDEBAR_CATEGORY: "Danh mục",
    SIDEBAR_FILTER: "Lọc theo",
    SIDEBAR_AUTHOR: "Tác giả",
    SIDEBAR_RATING: "Đánh giá",
    AVAILABLE_ONLY: "Chỉ hiển thị sách có sẵn",
    SORT_LABEL: "Sắp xếp",
    SORT_OPTIONS: {
        NEWEST: "Mới nhất",
        OLDEST: "Cũ nhất",
        TITLE: "Tên sách (A-Z)",
        TITLE_DESC: "Tên sách (Z-A)",
        AUTHOR: "Tác giả (A-Z)",
        AUTHOR_DESC: "Tác giả (Z-A)",
        MOST_READ: "Đọc nhiều nhất",
        LEAST_READ: "Đọc ít nhất",
    },
    AUTHOR_OPTIONS: {
        ALL: "Tất cả tác giả",
    },
    RATING_OPTIONS: {
        ALL: "Tất cả",
        UP_TO_4: "4 sao trở lên",
        UP_TO_3: "3 sao trở lên",
        UP_TO_2: "2 sao trở lên",
        UP_TO_1: "1 sao trở lên",
    },
    RESULTS_COUNT_PRE: "Hiển thị",
    RESULTS_COUNT_POST: "kết quả",
    RESULTS_FOR: "cho",
    IMAGE_ALT: "Bìa sách:",
    AUTHOR_LABEL: "Tác giả:",
    PUBLISHER_LABEL: "Nhà xuất bản:",
    NO_RESULTS_HEADING: "Không tìm thấy sách nào",
    NO_RESULTS_DESC: "Hãy thử thay đổi tiêu chí tìm kiếm hoặc danh mục để xem thêm kết quả.",
    CLEAR_FILTER_BTN: "Xóa bộ lọc",
    CATEGORIES: {
        ALL: "Tất cả",
        SCIENCE: "Khoa học & Công nghệ",
        FICTION: "Tiểu thuyết",
        HISTORY: "Lịch sử",
        DESIGN: "Thiết kế & Nghệ thuật",
        BUSINESS: "Kinh doanh",
    },
};

export const BOOK_DETAIL = {
    RELATED_BOOKS_HEADING: "Sách liên quan",
    VIEW_ALL: "Xem tất cả",
    IMAGE_ALT: "Bìa sách:",
    REVIEWS: "Reviews",
    BY: "By",
    TAGS_CATEGORIES: "Tags & Categories",
    METADATA: {
        PUBLISHER: "Publisher",
        PUBLISHED: "Published",
        PAGES: "Pages",
        ISBN: "ISBN",
        DEPOSIT: "Deposit",
        RENTAL_FEE: "Phí mượn",
        RENTAL_FEE_VALUE: "5.000 đ/ngày",
    },
    MATCH_SCORE_SUFFIX: "% Match",
    BORROW_NOW: "Borrow Now",
    RESERVE_NOW: "Đặt giữ chỗ",
    RESERVE_SUCCESS: "Đặt giữ chỗ thành công. Bạn đang ở vị trí thứ {position} trong hàng đợi.",
    RESERVE_ERROR: "Có lỗi xảy ra khi đặt giữ chỗ",
    ADD_WISHLIST: "Add to Wishlist",
    REMOVE_WISHLIST: "Remove from Wishlist",
    READ_AT_LIBRARY: "Đọc sách tại thư viện",
    REVIEW_BOOK: "Đánh giá sách",
    AI_CHATBOT: {
        TITLE: "Lumina AI",
        SUBTITLE: "Book Summary & Reading Path",
    },
    LOGIN_PROMPT: {
        TITLE: "Yêu cầu đăng nhập",
        DESCRIPTION: "Bạn cần đăng nhập để sử dụng tính năng này. Vui lòng đăng nhập hoặc tiếp tục khám phá sách.",
        LOGIN_BTN: "Đăng nhập ngay",
        CONTINUE_BTN: "Tiếp tục khám phá",
    },
};
