export const BORROW = {
    TITLE: "Yêu cầu mượn sách",
    SUBTITLE: "Xác nhận chi tiết mượn sách và chọn lịch lấy sách.",
    BACK_TO_CATALOG: "Trở lại danh mục",
    FORM: {
        SELECTED_TITLE: "Sách đã chọn",
        PICKUP_DATE: "Ngày lấy sách",
        RETURN_DATE: "Ngày trả sách",
        PAYMENT_METHOD: "Phương thức cọc",
        CASH: "Tiền mặt khi nhận",
        MOMO: "Ví MoMo",
        VNPAY: "Ví VNPay",
        GUEST_INFO_TITLE: "Thông tin người mượn (Khách)",
        GUEST_NAME_LABEL: "Họ và tên *",
        GUEST_PHONE_LABEL: "Số điện thoại *",
        GUEST_EMAIL_LABEL: "Email (Tùy chọn)",
        ERRORS: {
            MISSING_DATES: "Vui lòng chọn đầy đủ ngày đến lấy và ngày hoàn trả.",
            MISSING_GUEST_INFO: "Vui lòng nhập đầy đủ Họ tên và Số điện thoại.",
            SUBMIT_FAILED: "Đã xảy ra lỗi khi đặt mượn sách",
        },
    },
    POLICY: {
        TITLE: "Chính sách mượn sách:",
        CONTENT:
            "Mỗi độc giả được mượn tối đa 3 cuốn sách giấy. Vui lòng đảm bảo trả sách trong thời hạn 14 ngày để tránh phí phạt trễ hạn hoặc bị tạm khóa tài khoản.",
    },
    SUMMARY: {
        TITLE: "Tóm tắt mượn sách",
        BORROWER: "Người mượn",
        LOAN_PERIOD: "Thời hạn mượn",
        LOAN_PERIOD_VALUE: "14 Ngày",
        DAYS_SUFFIX: "Ngày",
        RENTAL_FEE: "Phí mượn sách",
        RENTAL_FEE_RATE: "Phí mượn / ngày",
        RENTAL_FEE_RATE_VALUE: "5.000đ / ngày",
        LATE_FEE_RATE: "Phí phạt trễ hạn",
        LATE_FEE_RATE_VALUE: "10.000đ / ngày",
        REFUNDABLE_DEPOSIT: "Tiền cọc (Hoàn lại)",
        CURRENCY: "đ",
        CONFIRM_BUTTON: "Xác nhận yêu cầu mượn",
        PROCESSING: "Đang xử lý...",
        SUCCESS: "Đã gửi yêu cầu!",
        SECURED_BY: "Bảo mật bởi Lumina Intelligence",
    },
    SUPPORT: {
        TITLE: "Cần hỗ trợ?",
        DESCRIPTION: "Thủ thư AI của chúng tôi làm việc 24/7 để giải đáp thắc mắc về địa điểm lấy sách và gia hạn.",
        BUTTON: "Mở Chat Thư viện",
    },
    SUPPORT_CHAT: {
        TITLE: "Lumina AI",
        SUBTITLE: "Book Summary & Reading Path",
        GREETING_PREFIX: "Xin chào! 👋 Mình là ",
        ASSISTANT_NAME: "Lumina Assistant",
        GREETING_SUFFIX: ", trợ lý ảo đồng hành cùng bạn tại thư viện. Mình có thể giúp bạn giải đáp các câu hỏi về thông tin sách, quy định thư viện hoặc quy trình mượn trả. Bạn cần hỗ trợ gì hôm nay nào?",
        PLACEHOLDER: "Mình có thể giúp gì cho bạn hôm nay?",
    },
    SUCCESS_PAGE: {
        TITLE: "Gửi yêu cầu mượn thành công!",
        REQUEST_ID: "Mã yêu cầu",
        PENDING_APPROVAL: "Yêu cầu mượn sách của bạn đang chờ đội ngũ quản lý phê duyệt. Một email xác nhận đã được gửi đến hộp thư của bạn.",
        VIEW_LOANS: "Xem sách đang mượn",
        CONTINUE_BROWSING: "Tiếp tục tìm sách",
        HOW_LONG: "Quá trình phê duyệt mất bao lâu?",
    },
    LOAN_DETAIL: {
        TITLE: "Chi tiết mượn sách",
        OVERDUE: "Quá hạn",
        TRANSACTION_ID: "Mã giao dịch:",
        CONTACT_LIBRARIAN: "Liên hệ thủ thư",
        CANNOT_RENEW: "Không thể gia hạn khi đã quá hạn",
        RENEW_LOAN: "Gia hạn mượn",
        OVERVIEW: "Tổng quan",
        BORROW_DATE: "Ngày mượn",
        DUE_DATE: "Hạn trả",
        ACTUAL_RETURN_DATE: "Ngày trả thực tế",
        STATUS: "Tình trạng",
        OVERDUE_DAYS: "Quá hạn",
        BORROWED_BOOKS: "Sách đã mượn",
        IN_USE: "Đang sử dụng",
        RETURNED: "Đã trả",
        FINANCIALS: "Chi phí & Phạt",
        DEPOSIT: "Tiền cọc (Đã thanh toán)",
        RENTAL_FEE: "Tiền mượn sách (Thanh toán khi trả)",
        LATE_FEE: "Phí quá hạn",
        TOTAL_PAYMENT: "Tổng thanh toán khi trả sách:",
        PAY_NOW: "Thanh toán ngay",
        ACTIVITY_HISTORY: "Lịch sử hoạt động",
        DEADLINE: "Hạn chót trả sách",
        REMINDER_SENT: "Gửi thông báo nhắc nhở",
        BORROW_SUCCESS: "Mượn sách thành công",
        DEPOSIT_FORFEITED: "(Đã trừ do quá hạn)",
        DEPOSIT_PAID: "",
        TOTAL_BORROW_FEE: "Tổng phí mượn",
        TOTAL_LATE_FEE: "Tổng phí phạt phát sinh",
        PAID_ONLINE: "Đã thanh toán",
        TO_PAY: "Cần thanh toán",
        LIMIT_MODAL_TITLE: "Không thể gia hạn",
        LIMIT_MODAL_DESC: "Phiếu mượn này đã được gia hạn tối đa 2 lần. Bạn không thể tiếp tục gia hạn thêm. Vui lòng mang sách đến thư viện để trả đúng hạn.",
        LIMIT_MODAL_ACKNOWLEDGE: "Đã hiểu",
    },
    VNPAY_RESULT: {
        SUCCESS: {
            TITLE: "Thanh toán thành công!",
            DESCRIPTION: "Tiền đặt cọc đã được thanh toán qua VNPay. Yêu cầu mượn sách của bạn đang chờ phê duyệt.",
            ORDER_CODE: "Mã đơn mượn",
            VIEW_LOANS: "Xem lịch sử mượn",
            CONTINUE_BROWSING: "Tiếp tục tìm sách",
        },
        FAILED: {
            TITLE: "Thanh toán thất bại",
            DESCRIPTION: "Giao dịch VNPay không thành công. Đơn mượn sách đã được hủy tự động. Bạn có thể thử lại.",
            ORDER_CODE: "Mã đơn mượn",
            TRY_AGAIN: "Thử lại",
            BACK_TO_HOME: "Về trang chủ",
        },
        LOADING: "Đang xử lý kết quả thanh toán...",
        BRAND: "VNPay",
        RECEIPT: {
            TITLE: "Chi tiết giao dịch (Biên lai)",
            TRANSACTION_ID: "Mã giao dịch VNPay:",
            TIME: "Thời gian:",
            CONTENT: "Nội dung:",
            AMOUNT: "Số tiền thanh toán:",
        },
    },
    TRA_CUU: {
        TITLE: "Tra cứu đơn mượn",
        DESC: "Dành cho khách vãng lai chưa có tài khoản.",
        ORDER_CODE_LABEL: "Mã đơn mượn",
        PHONE_LABEL: "Số điện thoại",
        SEARCH_BTN: "Tra cứu",
        HAVE_ACCOUNT: "Bạn đã có tài khoản?",
        LOGIN_NOW: "Đăng nhập ngay",
        NOT_FOUND: "Không tìm thấy đơn mượn.",
        MISSING_INFO: "Vui lòng nhập đầy đủ mã đơn mượn và số điện thoại.",
        INVALID_PHONE: "Số điện thoại không hợp lệ. Vui lòng nhập số điện thoại Việt Nam (10 số).",
        CONSOLE_ERROR: "Lỗi tra cứu đơn mượn:",
        LOOKUP_FAILED: "Tra cứu thất bại. Vui lòng kiểm tra lại thông tin.",
        RESULT: {
            TITLE: "Kết quả tra cứu",
            STATUS: "Trạng thái:",
            DUE_DATE: "Ngày hẹn trả:",
        },
    },
};
