export const CONTACT = {
    PAGE_TITLE: "Liên hệ | Lumina Library",
    PAGE_DESC: "Liên hệ với đội ngũ Lumina Library — giải đáp thắc mắc về thư viện, sách và các thông tin khác",
    HEADING: "Liên hệ với chúng tôi",
    SUBHEADING: "Bạn có câu hỏi về bộ sưu tập, khả năng tìm kiếm AI, hoặc truy cập tổ chức? Đội ngũ tận tâm của chúng tôi luôn sẵn sàng hỗ trợ bạn.",
    FORM_HEADING: "Gửi tin nhắn",
    NAME_LABEL: "Họ và tên",
    NAME_PLACEHOLDER: "Nguyễn Văn A",
    EMAIL_LABEL: "Địa chỉ Email",
    SUBJECT_LABEL: "Chủ đề",
    SUBJECT_OPTIONS: {
        DEFAULT: "Chọn loại yêu cầu...",
        ACCESS: "Truy cập Tổ chức",
        TECH_SUPPORT: "Hỗ trợ Kỹ thuật (Tìm kiếm AI)",
        COLLECTION: "Đề xuất Bộ sưu tập",
        OTHER: "Yêu cầu khác",
    },
    MESSAGE_LABEL: "Nội dung",
    MESSAGE_PLACEHOLDER: "Chúng tôi có thể hỗ trợ bạn điều gì?",
    SUBMIT_BTN: "Gửi yêu cầu",
    INFO_HEADING: "Thông tin liên hệ",
    ADDRESS_LABEL: "Địa chỉ",
    ADDRESS_LINE_1: "Lumina Campus",
    ADDRESS_LINE_2: "404 Knowledge Parkway",
    ADDRESS_LINE_3: "Innovation District, CA 90210",
    SUPPORT_LABEL: "Hỗ trợ chung",
    PHONE: "+1 (800) 555-0199",
    INFO_EMAIL_LABEL: "Email",
    EMAIL: "research@luminalibrary.edu",
    DIRECTIONS_BTN: "Chỉ đường",
    MAP_ALT: "Bản đồ vị trí Lumina Campus",
    FAQ_HEADING: "Câu hỏi thường gặp",
    FAQ_SUBHEADING: "Giải đáp nhanh các thắc mắc phổ biến.",
    FAQS: [
        {
            QUESTION: "Làm thế nào để mượn sách từ thư viện thông qua website?",
            ANSWER: "Bạn chỉ cần vào danh mục, tìm kiếm sách, chọn sách muốn mượn và chờ nhân viên thư viện xử lý nếu mượn sách trực tuyến. Sau đó, bạn có thể nhận sách tại quầy hoặc yêu cầu giao sách đến tận nơi.",
        },
        {
            QUESTION: "Tôi có thể mượn sách dễ dàng không?",
            ANSWER: "Có, Lumina Library cho phép mượn sách dễ dàng thông qua website hoặc mượn trực tiếp từ thư viện",
        },
        {
            QUESTION: "Giờ hoạt động của thư viện là bao nhiêu?",
            ANSWER: "Các phòng đọc tại thư viện mở cửa từ Thứ Hai đến Thứ Sáu, 8:00 sáng đến 9:00 tối. Truy cập cuối tuần được giới hạn cho các nghiên cứu sinh cao cấp theo lịch hẹn. Danh mục kỹ thuật số hoạt động 24/7.",
        },
    ],
};
