export const HOME = {
    HERO_HEADING: "TÌM KIẾM TRI THỨC CÙNG AI",
    HERO_SUBHEADING: "Tìm kiếm những cuốn sách yêu thích của bạn dễ dàng hơn với công nghệ AI.",
    HERO_TAGS: ["Tiểu thuyết", "Lập trình", "Lịch sử", "Khoa học"],
    SEARCH_PLACEHOLDER: "Tìm kiếm sách...",
    SEARCH_BTN: "Tìm kiếm với AI",
    LABEL_AI_POWERED: "AI-Powered Library",
    TRENDING_LABEL: "Xu hướng:",
    STATS_TOTAL_BOOKS: "Tổng bộ sưu tập",
    STATS_TOTAL_DESC: "đầu sách đa thể loại",
    STATS_AI_SEARCH: "Tìm kiếm AI",
    STATS_AI_DESC: "độ chính xác gợi ý",
    VIEW_DETAILS: "Xem chi tiết →",
    CURATED_HEADING: "Dành cho bạn",
    CURATED_SUBHEADING: "Đề xuất dựa trên sở thích đọc sách của bạn.",
    MATCH_SUFFIX: "% phù hợp.",
    EXPLORE_COLLECTION: "Khám phá bộ sưu tập",
    TRENDING_HEADING: "Đang thịnh hành",
    TRENDING_SUBHEADING: "Xu hướng hiện tại.",
    TOP_RATED_HEADING: "Đánh giá cao nhất",
    TOP_RATED_SUBHEADING: "Những tựa sách được độc giả yêu thích nhất.",
    NEWEST_HEADING: "Sách mới nhất",
    NEWEST_SUBHEADING: "Khám phá những ấn phẩm vừa ra mắt.",
    VIEW_ALL: "Xem tất cả",
    CATEGORIES: {
        SCIENCE: "Khoa học",
        NOVEL: "Tiểu thuyết",
        HISTORY: "Lịch sử",
        DESIGN: "Thiết kế",
    },
    BADGES: {
        TRENDING_1: "#1 Thịnh hành",
    },
    CURATED_SECTION: {
        DEEP_DIVE: "Deep Dive",
        PHILOSOPHY_AI: "The Philosophy of Artificial Intelligence",
        PHILOSOPHY_AI_DESC: "A comprehensive collection exploring the ethical and societal implications of thinking machines.",
        HARD_SCIFI: "Hard Sci-Fi Essentials",
        HARD_SCIFI_DESC: "Highly technical speculative fiction based on your recent searches.",
        BOOKS_12: "12 Books",
        WORLD_BUILDING: "World Building Masterclass",
        WORLD_BUILDING_DESC: "Because you read 'Dune' and 'Foundation'.",
        REFRESH_BTN: "Làm mới gợi ý",
        DISMISS: "Bỏ qua",
        WISHLIST_ADDED: "Đã thêm vào danh sách yêu thích",
        WISHLIST_REMOVED: "Đã bỏ khỏi danh sách yêu thích",
        LOGIN_CTA_TITLE: "Cá nhân hóa trải nghiệm của bạn",
        LOGIN_CTA_SUBTITLE: "Đăng nhập để nhận gợi ý sách dựa trên sở thích và lịch sử đọc của bạn.",
        LOGIN_BTN: "Đăng nhập ngay",
        GUEST_COLLECTION_1: "Khoa học & Công nghệ",
        GUEST_COLLECTION_1_DESC: "Những đầu sách khoa học phổ biến nhất hiện nay.",
        GUEST_COLLECTION_2: "Văn học kinh điển",
        GUEST_COLLECTION_2_DESC: "Tác phẩm được độc giả yêu thích nhiều nhất.",
        LOADING: "Đang phân tích sở thích của bạn...",
        VIEW_CATEGORY: "Xem tất cả",
        BOOKS_COUNT: (n: number) => `${n} đầu sách`,
        PERSONALIZED_LABEL: "Dành riêng cho bạn",
        BASED_ON_HISTORY: "Dựa trên lịch sử mượn sách",
        BASED_ON_FAVORITES: "Dựa trên sách yêu thích",
        FAVORITE_DESC: "Dựa trên những cuốn sách bạn đã thêm vào danh sách yêu thích.",
        GUEST_TRENDING: "Đang thịnh hành",
        GUEST_TRENDING_DESC: "Những cuốn sách đang được mượn nhiều nhất hiện nay.",
        GUEST_NEWEST: "Sách mới ra mắt",
        GUEST_NEWEST_DESC: "Những ấn phẩm vừa được bổ sung vào thư viện.",
        GUEST_SUBHEADING: "Đăng nhập để nhận gợi ý dành riêng cho bạn.",
        ERROR_LOAD: "Không thể tải gợi ý. Vui lòng thử lại.",
        RETRY: "Thử lại",
        EMPTY_STATE: "Bạn đã bỏ qua tất cả gợi ý.",
    },
};
