export const MY_BOOKS_PAGE = {
    TITLE: "Lịch sử mượn sách",
    BREADCRUMB_ACCOUNT: "Tài khoản",
    STATUS_OVERDUE: "Quá hạn (3 ngày)",
    RENEW_NOW: "Gia hạn ngay",
    FILTER: {
        STATUS_LABEL: "Trạng thái",
        STATUS_ALL: "Tất cả trạng thái",
        STATUS_BORROWING: "Đang mượn",
        STATUS_RETURNED: "Đã trả",
        STATUS_OVERDUE: "Quá hạn",
        STATUS_PENDING: "Chờ phê duyệt",
        STATUS_CANCELLED: "Đã hủy",
        DATE_RANGE_LABEL: "Khoảng thời gian",
        DATE_TO: "đến",
        APPLY_BUTTON: "Áp dụng bộ lọc",
    },
    CARD: {
        AUTHOR_PREFIX: "Tác giả:",
        BORROW_DATE: "Ngày mượn",
        DUE_DATE: "Hạn trả dự kiến",
        ACTUAL_RETURN_DATE: "Ngày trả thực tế",
        DEPOSIT: "Tiền đặt cọc",
        LATE_FEE_LABEL: "Tiền phạt phát sinh",
        DEPOSIT_RETURN: "Hoàn trả cọc",
        VIEW_DETAIL: "Xem chi tiết",
        VIEW_RECEIPT: "Xem biên lai",
        STATUS_BORROWING: "Đang mượn",
        STATUS_RETURNED: "Đã trả",
    },
    EMPTY_STATE: {
        HEADING: "Bạn chưa có lịch sử mượn sách",
        DESC: "Hãy bắt đầu hành trình khám phá kho tri thức khổng lồ của Lumina Library ngay hôm nay.",
        BROWSE_BUTTON: "Duyệt kho sách ngay",
    },
    FILTER_EMPTY_STATE: {
        HEADING: "Không tìm thấy kết quả",
        DESC: "Vui lòng thử thay đổi điều kiện lọc.",
    },
};

export const RENEW_PAGE = {
    TITLE: "Gia hạn sách",
    BREADCRUMB_ACCOUNT: "Tài khoản",
    BREADCRUMB_HISTORY: "Lịch sử mượn sách",
    BREADCRUMB_RENEW: "Gia hạn sách",
    OVERDUE_BADGE_PREFIX: "Quá hạn",
    OVERDUE_DAYS_SUFFIX: "ngày",
    AUTHOR_PREFIX: "Tác giả:",
    BORROW_DATE: "NGÀY MƯỢN",
    DUE_DATE: "HẠN TRẢ DỰ KIẾN",
    ACTUAL_RETURN_DATE: "NGÀY TRẢ THỰC TẾ",
    ACTUAL_RETURN_DASH: "—",
    DETAIL: {
        HEADING: "Chi tiết gia hạn",
        CURRENT_LATE_FEE: "Phí phạt hiện tại:",
        INITIAL_DEPOSIT: "Tiền đặt cọc ban đầu:",
    },
    DURATION: {
        HEADING: "Chọn thời gian gia hạn",
        DAYS_SUFFIX: "ngày",
        FEE_PREFIX: "+",
        FEE_SUFFIX: "đ",
    },
    SUMMARY: {
        TOTAL_NEW_COST: "Tổng chi phí mới:",
        INITIAL_DEPOSIT_LABEL: "Tiền đặt cọc ban đầu:",
        TOTAL_LABEL: "Tổng chi phí mới:",
    },
    CONFIRM_BUTTON: "Xác nhận gia hạn",
};
